import jsPDF from 'jspdf';

export interface ComplaintExportData {
  reference_number: string;
  category: string;
  subcategory: string;
  title: string;
  description: string;
  locality: string;
  district: string;
  state: string;
  constituency?: string;
  severity: string;
  status: string;
  submitter_name: string;
  submitter_email: string;
  submitter_phone?: string;
  created_at: string;
  updated_at: string;
}

export function exportComplaintPDF(data: ComplaintExportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = 18;

  const checkPageBreak = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Makkal Kural - Complaint Report', margin, y);
  y += 10;

  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  const fields: { label: string; value: string }[] = [
    { label: 'Reference Number', value: data.reference_number },
    { label: 'Status', value: data.status },
    { label: 'Category', value: `${data.category} > ${data.subcategory}` },
    { label: 'Severity', value: data.severity },
    { label: 'Location', value: `${data.locality}, ${data.district}, ${data.state}${data.constituency ? ` (${data.constituency})` : ''}` },
    { label: 'Submitted By', value: `${data.submitter_name} | ${data.submitter_email}${data.submitter_phone ? ` | ${data.submitter_phone}` : ''}` },
    { label: 'Created At', value: new Date(data.created_at).toLocaleString() },
    { label: 'Last Updated', value: new Date(data.updated_at).toLocaleString() },
  ];

  doc.setFontSize(11);
  fields.forEach((field) => {
    checkPageBreak(14);
    doc.setFont('helvetica', 'bold');
    doc.text(field.label, margin, y);
    doc.setFont('helvetica', 'normal');
    const valueLines = doc.splitTextToSize(field.value, pageWidth - margin * 2);
    doc.text(valueLines, margin, y + 5);
    y += 5 + valueLines.length * 5 + 4;
  });

  y += 4;
  checkPageBreak(14);
  doc.setDrawColor(0);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.text('Title', margin, y);
  doc.setFont('helvetica', 'normal');
  const titleLines = doc.splitTextToSize(data.title, pageWidth - margin * 2);
  doc.text(titleLines, margin, y + 5);
  y += 5 + titleLines.length * 5 + 6;

  checkPageBreak(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Description', margin, y);
  doc.setFont('helvetica', 'normal');
  const descLines = doc.splitTextToSize(data.description, pageWidth - margin * 2);
  doc.text(descLines, margin, y + 5);
  y += 5 + descLines.length * 5 + 6;

  checkPageBreak(14);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`Generated by Makkal Kural on ${new Date().toLocaleString()}`, margin, y);

  doc.save(`complaint-${data.reference_number}.pdf`);
}

export function exportComplaintsCSV(complaints: ComplaintExportData[]) {
  if (!complaints.length) return;
  const headers = [
    'Reference Number',
    'Status',
    'Category',
    'Subcategory',
    'Severity',
    'Title',
    'Description',
    'Locality',
    'District',
    'State',
    'Constituency',
    'Submitter Name',
    'Submitter Email',
    'Submitter Phone',
    'Created At',
    'Updated At',
  ];

  const escape = (val: string) => `"${val.replace(/"/g, '""')}"`;
  const rows = complaints.map((c) =>
    [
      c.reference_number,
      c.status,
      c.category,
      c.subcategory,
      c.severity,
      c.title,
      c.description,
      c.locality,
      c.district,
      c.state,
      c.constituency || '',
      c.submitter_name,
      c.submitter_email,
      c.submitter_phone || '',
      c.created_at,
      c.updated_at,
    ]
      .map(escape)
      .join(',')
  );

  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `complaints-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
