import { Complaint, Representative, DeliveryLog, ComplaintUpdate } from '@/types/database';

export const INITIAL_REPRESENTATIVES: Representative[] = [
  {
    id: 'rep-gcc-01',
    name: 'Commissioner Office, Greater Chennai Corporation',
    role: 'Commissioner / Grievance Cell',
    organization: 'Greater Chennai Corporation (GCC)',
    category_specialty: 'Garbage, Roads, Drainage, Street Lights',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'commissioner@chennaicorporation.gov.in',
    x_handle: 'chennaicorp',
    official_website: 'https://chennaicorporation.gov.in',
    source_url: 'https://erp.chennaicorporation.gov.in/pgr/',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rep-tneb-01',
    name: 'Chief Engineer (Distribution) - Chennai South',
    role: 'Chief Distribution Engineer',
    organization: 'TANGEDCO (Tamil Nadu Electricity Board)',
    category_specialty: 'Electricity',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'Mylapore, Velachery, T.Nagar, Sholinganallur',
    email: 'cedsouth@tnebnet.org',
    x_handle: 'TANGEDCO_Offcl',
    official_website: 'https://www.tnpdcl.org',
    source_url: 'https://www.tnpdcl.org/en/tnpdcl/reach-us/contact-information/',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rep-cmwssb-01',
    name: 'Chennai Metro Water - Operations Department',
    role: 'Executive Director (Water Supply & Sewerage)',
    organization: 'Chennai Metropolitan Water Supply and Sewerage Board (CMWSSB)',
    category_specialty: 'Water, Drainage',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'cmwssb@tn.gov.in',
    x_handle: 'CMWSSB_Official',
    official_website: 'https://cmwssb.tn.gov.in',
    source_url: 'https://cmwssb.tn.gov.in/complaints',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rep-ccmc-01',
    name: 'Commissioner, Coimbatore City Municipal Corporation',
    role: 'Municipal Commissioner',
    organization: 'Coimbatore City Municipal Corporation',
    category_specialty: 'Roads, Water, Garbage, Drainage',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    constituency: 'Coimbatore South, Coimbatore North, Singanallur',
    email: 'commr.coimbatore@tn.gov.in',
    x_handle: 'CbeCityCorp',
    official_website: 'https://ccmc.gov.in',
    source_url: 'https://ccmc.gov.in/index.php/contact-us',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-05T11:30:00Z',
  },
  {
    id: 'rep-madurai-01',
    name: 'Commissioner, Madurai Municipal Corporation',
    role: 'Corporation Commissioner',
    organization: 'Madurai Municipal Corporation',
    category_specialty: 'Roads, Drainage, Water, Healthcare',
    state: 'Tamil Nadu',
    district: 'Madurai',
    constituency: 'Madurai North, Madurai South, Madurai Central, Madurai West',
    email: 'commr.madurai@tn.gov.in',
    x_handle: 'MaduraiCorp',
    official_website: 'https://www.maduraicorporation.co.in',
    source_url: 'https://maduraicorporation.co.in/contact-us/',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-10T09:00:00Z',
  },
  {
    id: 'rep-trichy-01',
    name: 'Commissioner, Tiruchirappalli City Corporation',
    role: 'Corporation Commissioner',
    organization: 'Tiruchirappalli City Corporation',
    category_specialty: 'Roads, Water, Garbage, Public Safety',
    state: 'Tamil Nadu',
    district: 'Tiruchirappalli',
    constituency: 'Tiruchirappalli West, Tiruchirappalli East, Srirangam',
    email: 'commr.trichy@tn.gov.in',
    x_handle: 'TrichyCorp',
    official_website: 'https://www.trichycorporation.gov.in',
    source_url: 'https://www.trichycorporation.gov.in/contact',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-12T14:20:00Z',
  },
  {
    id: 'rep-salem-01',
    name: 'Commissioner, Salem City Municipal Corporation',
    role: 'Municipal Commissioner',
    organization: 'Salem City Municipal Corporation',
    category_specialty: 'Roads, Drainage, Street Lights, Garbage',
    state: 'Tamil Nadu',
    district: 'Salem',
    constituency: 'Salem North, Salem South, Salem West',
    email: 'commr.salem@tn.gov.in',
    x_handle: 'SalemCorp',
    official_website: 'https://www.salemcorporation.gov.in',
    source_url: 'https://www.salemcorporation.gov.in/contact.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-14T10:00:00Z',
  },
  {
    id: 'rep-tirunelveli-01',
    name: 'Commissioner, Tirunelveli City Municipal Corporation',
    role: 'Municipal Commissioner',
    organization: 'Tirunelveli Corporation',
    category_specialty: 'Roads, Water, Sanitation, Transport',
    state: 'Tamil Nadu',
    district: 'Tirunelveli',
    constituency: 'Tirunelveli, Palayamkottai',
    email: 'commr.tirunelveli@tn.gov.in',
    x_handle: 'TirunelveliCorp',
    official_website: 'https://www.tirunelvelicorporation.com',
    source_url: 'https://www.tirunelvelicorporation.com/contact-us',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-07-25T12:00:00Z',
  },
  {
    id: 'rep-kanchi-01',
    name: 'District Collector & Magistrate, Kanchipuram',
    role: 'District Collector',
    organization: 'Kanchipuram District Administration',
    category_specialty: 'Government Services, Transport, Environment',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    constituency: 'Kanchipuram, Sriperumbudur, Uthiramerur',
    email: 'collr-knc@nic.in',
    x_handle: 'KanchiCollector',
    official_website: 'https://kancheepuram.nic.in',
    source_url: 'https://kancheepuram.nic.in/citizen-charter',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-15T08:30:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-15T08:30:00Z',
  },
  {
    id: 'rep-thanjavur-01',
    name: 'District Collector, Thanjavur',
    role: 'District Collector',
    organization: 'Thanjavur District Administration',
    category_specialty: 'Water, Agriculture, Roads',
    state: 'Tamil Nadu',
    district: 'Thanjavur',
    constituency: 'Thanjavur, Kumbakonam, Papanasam, Orathanadu',
    email: 'collr-tj@nic.in',
    x_handle: 'TnjCollector',
    official_website: 'https://thanjavur.nic.in',
    source_url: 'https://thanjavur.nic.in/departments',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-07-30T11:00:00Z',
  },
  {
    id: 'rep-collector-erode-01',
    name: 'District Collector & Magistrate, Erode',
    role: 'District Collector',
    organization: 'Erode District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Erode',
    constituency: 'Erode East, Erode West, Modakkurichi, Perundurai, Bhavani',
    email: 'collr-erode@nic.in',
    x_handle: 'ErodeCollector',
    official_website: 'https://erode.nic.in',
    source_url: 'https://erode.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tiruppur-01',
    name: 'District Collector & Magistrate, Tiruppur',
    role: 'District Collector',
    organization: 'Tiruppur District Administration',
    category_specialty: 'Textiles, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    constituency: 'Tiruppur North, Tiruppur South, Palladam, Udumalaipettai',
    email: 'collr-tiruppur@nic.in',
    x_handle: 'TiruppurCollector',
    official_website: 'https://tiruppur.nic.in',
    source_url: 'https://tiruppur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-vellore-01',
    name: 'District Collector & Magistrate, Vellore',
    role: 'District Collector',
    organization: 'Vellore District Administration',
    category_specialty: 'Healthcare, Education, Public Services',
    state: 'Tamil Nadu',
    district: 'Vellore',
    constituency: 'Vellore, Anaikattu, Kilvaithinankuppam, Gudiyattam',
    email: 'collr-vellore@nic.in',
    x_handle: 'VelloreCollector',
    official_website: 'https://vellore.nic.in',
    source_url: 'https://vellore.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-dindigul-01',
    name: 'District Collector & Magistrate, Dindigul',
    role: 'District Collector',
    organization: 'Dindigul District Administration',
    category_specialty: 'Agriculture, Tourism, Public Services',
    state: 'Tamil Nadu',
    district: 'Dindigul',
    constituency: 'Dindigul, Palani, Oddanchatram, Athoor, Nilakkottai',
    email: 'collr-dindigul@nic.in',
    x_handle: 'DindigulCollector',
    official_website: 'https://dindigul.nic.in',
    source_url: 'https://dindigul.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-cuddalore-01',
    name: 'District Collector & Magistrate, Cuddalore',
    role: 'District Collector',
    organization: 'Cuddalore District Administration',
    category_specialty: 'Ports, Industries, Agriculture',
    state: 'Tamil Nadu',
    district: 'Cuddalore',
    constituency: 'Cuddalore, Panruti, Chidambaram, Kattumannarkoil',
    email: 'collr-cuddalore@nic.in',
    x_handle: 'CuddaloreCollector',
    official_website: 'https://cuddalore.nic.in',
    source_url: 'https://cuddalore.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-thoothukudi-01',
    name: 'District Collector & Magistrate, Thoothukudi',
    role: 'District Collector',
    organization: 'Thoothukudi District Administration',
    category_specialty: 'Ports, Shipping, Salt',
    state: 'Tamil Nadu',
    district: 'Thoothukudi',
    constituency: 'Thoothukudi, Tiruchendur, Srivaikuntam, Ottapidaram',
    email: 'collr-thoothukudi@nic.in',
    x_handle: 'ThoothukudiCollector',
    official_website: 'https://thoothukudi.nic.in',
    source_url: 'https://thoothukudi.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-kanyakumari-01',
    name: 'District Collector & Magistrate, Kanyakumari',
    role: 'District Collector',
    organization: 'Kanyakumari District Administration',
    category_specialty: 'Tourism, Fisheries, Public Services',
    state: 'Tamil Nadu',
    district: 'Kanyakumari',
    constituency: 'Kanyakumari, Nagercoil, Colachel, Padmanabhapuram',
    email: 'collr-kanyakumari@nic.in',
    x_handle: 'KanyakumariCollector',
    official_website: 'https://kanyakumari.nic.in',
    source_url: 'https://kanyakumari.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-dharmapuri-01',
    name: 'District Collector & Magistrate, Dharmapuri',
    role: 'District Collector',
    organization: 'Dharmapuri District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri, Palacodu, Pennagaram, Harur',
    email: 'collr-dharmapuri@nic.in',
    x_handle: 'DharmapuriCollector',
    official_website: 'https://dharmapuri.nic.in',
    source_url: 'https://dharmapuri.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-krishnagiri-01',
    name: 'District Collector & Magistrate, Krishnagiri',
    role: 'District Collector',
    organization: 'Krishnagiri District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    constituency: 'Krishnagiri, Hosur, Uthangarai, Bargur',
    email: 'collr-krishnagiri@nic.in',
    x_handle: 'KrishnagiriCollector',
    official_website: 'https://krishnagiri.nic.in',
    source_url: 'https://krishnagiri.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-namakkal-01',
    name: 'District Collector & Magistrate, Namakkal',
    role: 'District Collector',
    organization: 'Namakkal District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Namakkal',
    constituency: 'Namakkal, Rasipuram, Senthamangalam, Paramathi-Velur',
    email: 'collr-namakkal@nic.in',
    x_handle: 'NamakkalCollector',
    official_website: 'https://namakkal.nic.in',
    source_url: 'https://namakkal.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-villupuram-01',
    name: 'District Collector & Magistrate, Villupuram',
    role: 'District Collector',
    organization: 'Villupuram District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Villupuram',
    constituency: 'Villupuram, Vikravandi, Tindivanam, Vanur',
    email: 'collr-villupuram@nic.in',
    x_handle: 'VillupuramCollector',
    official_website: 'https://villupuram.nic.in',
    source_url: 'https://villupuram.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-nagapattinam-01',
    name: 'District Collector & Magistrate, Nagapattinam',
    role: 'District Collector',
    organization: 'Nagapattinam District Administration',
    category_specialty: 'Fisheries, Ports, Public Services',
    state: 'Tamil Nadu',
    district: 'Nagapattinam',
    constituency: 'Nagapattinam, Kilvelur, Vedaranyam',
    email: 'collr-nagapattinam@nic.in',
    x_handle: 'NagapattinamCollector',
    official_website: 'https://nagapattinam.nic.in',
    source_url: 'https://nagapattinam.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-pudukkottai-01',
    name: 'District Collector & Magistrate, Pudukkottai',
    role: 'District Collector',
    organization: 'Pudukkottai District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Pudukkottai',
    constituency: 'Pudukkottai, Gandarvakottai, Viralimalai, Thirumayam',
    email: 'collr-pudukkottai@nic.in',
    x_handle: 'PudukkottaiCollector',
    official_website: 'https://pudukkottai.nic.in',
    source_url: 'https://pudukkottai.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-ramanathapuram-01',
    name: 'District Collector & Magistrate, Ramanathapuram',
    role: 'District Collector',
    organization: 'Ramanathapuram District Administration',
    category_specialty: 'Fisheries, Pilgrimage, Public Services',
    state: 'Tamil Nadu',
    district: 'Ramanathapuram',
    constituency: 'Ramanathapuram, Paramakudi, Tiruvadanai, Mudukulathur',
    email: 'collr-ramanathapuram@nic.in',
    x_handle: 'RamanathapuramCollector',
    official_website: 'https://ramanathapuram.nic.in',
    source_url: 'https://ramanathapuram.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-virudhunagar-01',
    name: 'District Collector & Magistrate, Virudhunagar',
    role: 'District Collector',
    organization: 'Virudhunagar District Administration',
    category_specialty: 'Industries, Commerce, Public Services',
    state: 'Tamil Nadu',
    district: 'Virudhunagar',
    constituency: 'Virudhunagar, Sivakasi, Sattur, Aruppukkottai',
    email: 'collr-virudhunagar@nic.in',
    x_handle: 'VirudhunagarCollector',
    official_website: 'https://virudhunagar.nic.in',
    source_url: 'https://virudhunagar.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-sivaganga-01',
    name: 'District Collector & Magistrate, Sivaganga',
    role: 'District Collector',
    organization: 'Sivaganga District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Sivaganga',
    constituency: 'Sivaganga, Karaikudi, Tiruppattur, Manamadurai',
    email: 'collr-sivaganga@nic.in',
    x_handle: 'SivagangaCollector',
    official_website: 'https://sivaganga.nic.in',
    source_url: 'https://sivaganga.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-nilgiris-01',
    name: 'District Collector & Magistrate, The Nilgiris',
    role: 'District Collector',
    organization: 'The Nilgiris District Administration',
    category_specialty: 'Tourism, Environment, Public Services',
    state: 'Tamil Nadu',
    district: 'Nilgiris',
    constituency: 'Udhagamandalam, Coonoor, Gudalur',
    email: 'collr-nilgiris@nic.in',
    x_handle: 'NilgirisCollector',
    official_website: 'https://nilgiris.nic.in',
    source_url: 'https://nilgiris.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-theeni-01',
    name: 'District Collector & Magistrate, Theni',
    role: 'District Collector',
    organization: 'Theni District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Theni',
    constituency: 'Bodinayakanur, Periyakulam, Cumbum, Andipatti',
    email: 'collr-theni@nic.in',
    x_handle: 'TheniCollector',
    official_website: 'https://theni.nic.in',
    source_url: 'https://theni.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-karur-01',
    name: 'District Collector & Magistrate, Karur',
    role: 'District Collector',
    organization: 'Karur District Administration',
    category_specialty: 'Textiles, Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Karur',
    constituency: 'Karur, Aravakurichi, Krishnarayapuram, Kulithalai',
    email: 'collr-karur@nic.in',
    x_handle: 'KarurCollector',
    official_website: 'https://karur.nic.in',
    source_url: 'https://karur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-perambalur-01',
    name: 'District Collector & Magistrate, Perambalur',
    role: 'District Collector',
    organization: 'Perambalur District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Perambalur',
    constituency: 'Perambalur, Kunnam',
    email: 'collr-perambalur@nic.in',
    x_handle: 'PerambalurCollector',
    official_website: 'https://perambalur.nic.in',
    source_url: 'https://perambalur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-ariyalur-01',
    name: 'District Collector & Magistrate, Ariyalur',
    role: 'District Collector',
    organization: 'Ariyalur District Administration',
    category_specialty: 'Cement, Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Ariyalur',
    constituency: 'Ariyalur, Jayankondam',
    email: 'collr-ariyalur@nic.in',
    x_handle: 'AriyalurCollector',
    official_website: 'https://ariyalur.nic.in',
    source_url: 'https://ariyalur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-thiruvarur-01',
    name: 'District Collector & Magistrate, Thiruvarur',
    role: 'District Collector',
    organization: 'Thiruvarur District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Thiruvarur',
    constituency: 'Thiruvarur, Mannargudi, Thiruthuraipoondi, Nannilam',
    email: 'collr-thiruvarur@nic.in',
    x_handle: 'ThiruvarurCollector',
    official_website: 'https://thiruvarur.nic.in',
    source_url: 'https://thiruvarur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tiruvannamalai-01',
    name: 'District Collector & Magistrate, Tiruvannamalai',
    role: 'District Collector',
    organization: 'Tiruvannamalai District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Tiruvannamalai',
    constituency: 'Tiruvannamalai, Chengam, Polur, Arani',
    email: 'collr-tiruvannamalai@nic.in',
    x_handle: 'TiruvannamalaiCollector',
    official_website: 'https://tiruvannamalai.nic.in',
    source_url: 'https://tiruvannamalai.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-ranipet-01',
    name: 'District Collector & Magistrate, Ranipet',
    role: 'District Collector',
    organization: 'Ranipet District Administration',
    category_specialty: 'Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Ranipet',
    constituency: 'Ranipet, Arcot, Sholinghur, Arakkonam',
    email: 'collr-ranipet@nic.in',
    x_handle: 'RanipetCollector',
    official_website: 'https://ranipet.nic.in',
    source_url: 'https://ranipet.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tirupathur-01',
    name: 'District Collector & Magistrate, Tirupathur',
    role: 'District Collector',
    organization: 'Tirupathur District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Tirupathur',
    constituency: 'Tirupathur, Vaniyambadi, Ambur, Jolarpet',
    email: 'collr-tirupathur@nic.in',
    x_handle: 'TirupathurCollector',
    official_website: 'https://tirupathur.nic.in',
    source_url: 'https://tirupathur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-kallakurichi-01',
    name: 'District Collector & Magistrate, Kallakurichi',
    role: 'District Collector',
    organization: 'Kallakurichi District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Kallakurichi',
    constituency: 'Kallakurichi, Rishivandiyam, Sankarapuram, Ulundurpet',
    email: 'collr-kallakurichi@nic.in',
    x_handle: 'KallakurichiCollector',
    official_website: 'https://kallakurichi.nic.in',
    source_url: 'https://kallakurichi.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tenkasi-01',
    name: 'District Collector & Magistrate, Tenkasi',
    role: 'District Collector',
    organization: 'Tenkasi District Administration',
    category_specialty: 'Agriculture, Tourism, Public Services',
    state: 'Tamil Nadu',
    district: 'Tenkasi',
    constituency: 'Tenkasi, Kadayanallur, Vasudevanallur, Sankarankovil',
    email: 'collr-tenkasi@nic.in',
    x_handle: 'TenkasiCollector',
    official_website: 'https://tenkasi.nic.in',
    source_url: 'https://tenkasi.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-mayiladuthurai-01',
    name: 'District Collector & Magistrate, Mayiladuthurai',
    role: 'District Collector',
    organization: 'Mayiladuthurai District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Mayiladuthurai',
    constituency: 'Mayiladuthurai, Sirkazhi, Poompuhar',
    email: 'collr-mayiladuthurai@nic.in',
    x_handle: 'MayiladuthuraiCollector',
    official_website: 'https://mayiladuthurai.nic.in',
    source_url: 'https://mayiladuthurai.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-chengalpattu-01',
    name: 'District Collector & Magistrate, Chengalpattu',
    role: 'District Collector',
    organization: 'Chengalpattu District Administration',
    category_specialty: 'Industries, IT, Public Services',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    constituency: 'Chengalpattu, Tambaram, Pallavaram, Madurantakam',
    email: 'collr-chengalpattu@nic.in',
    x_handle: 'ChengalpattuCollector',
    official_website: 'https://chengalpattu.nic.in',
    source_url: 'https://chengalpattu.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-thiruvallur-01',
    name: 'District Collector & Magistrate, Thiruvallur',
    role: 'District Collector',
    organization: 'Thiruvallur District Administration',
    category_specialty: 'Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Thiruvallur',
    constituency: 'Thiruvallur, Avadi, Poonamallee, Ambattur',
    email: 'collr-thiruvallur@nic.in',
    x_handle: 'ThiruvallurCollector',
    official_website: 'https://thiruvallur.nic.in',
    source_url: 'https://thiruvallur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-minister-cm-01',
    name: 'Hon\'ble Chief Minister of Tamil Nadu',
    role: 'Chief Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'All Categories',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'cmoffice@tn.gov.in',
    x_handle: 'mkstalin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/government/chief-minister',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-minister-finance-01',
    name: 'Hon\'ble Minister for Finance & Human Resources',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Finance, Revenue, Public Services',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'finminister@tn.gov.in',
    x_handle: 'TNFinanceMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/government/council-of-ministers',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-mla-coimbatore-01',
    name: 'Hon\'ble MLA, Coimbatore North Constituency',
    role: 'MLA',
    organization: 'Tamil Nadu Legislative Assembly',
    category_specialty: 'Roads, Water, Infrastructure, Healthcare',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    constituency: 'Coimbatore North, Coimbatore South, Singanallur',
    email: 'mla.coimbatore-north@tn.gov.in',
    x_handle: 'MLACbeNorth',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://assembly.tn.gov.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-18T10:00:00Z',
  },
  {
    id: 'rep-mla-madurai-01',
    name: 'Hon\'ble MLA, Madurai Central Constituency',
    role: 'MLA',
    organization: 'Tamil Nadu Legislative Assembly',
    category_specialty: 'All Categories',
    state: 'Tamil Nadu',
    district: 'Madurai',
    constituency: 'Madurai North, Madurai South, Madurai Central, Madurai West',
    email: 'mla.madurai-central@tn.gov.in',
    x_handle: 'MLAMduCentral',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://assembly.tn.gov.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-19T11:00:00Z',
  },
  {
    id: 'rep-mla-trichy-01',
    name: 'Hon\'ble MLA, Tiruchirappalli West Constituency',
    role: 'MLA',
    organization: 'Tamil Nadu Legislative Assembly',
    category_specialty: 'Roads, Water, Public Safety, Electricity',
    state: 'Tamil Nadu',
    district: 'Tiruchirappalli',
    constituency: 'Tiruchirappalli West, Tiruchirappalli East, Srirangam',
    email: 'mla.trichy-west@tn.gov.in',
    x_handle: 'MLATrichyWest',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://assembly.tn.gov.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-21T14:00:00Z',
  },
  {
    id: 'rep-mla-salem-01',
    name: 'Hon\'ble MLA, Salem North Constituency',
    role: 'MLA',
    organization: 'Tamil Nadu Legislative Assembly',
    category_specialty: 'Roads, Drainage, Street Lights, Agriculture',
    state: 'Tamil Nadu',
    district: 'Salem',
    constituency: 'Salem North, Salem South, Salem West',
    email: 'mla.salem-north@tn.gov.in',
    x_handle: 'MLASalemNorth',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://assembly.tn.gov.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T08:00:00Z',
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'complaint-sample-01',
    reference_number: 'MK-2026-104829',
    category: 'roads',
    subcategory: 'Potholes',
    title: 'Severe crater potholes on Anna Salai service lane near Thousand Lights',
    description: 'Multiple deep potholes have formed on the service lane causing severe traffic slowdowns and motorbike skidding accidents during evening peak hours.',
    original_language: 'en',
    ai_improved_title: 'Urgent Road Repair Request: Pothole Hazards on Anna Salai Service Road',
    ai_improved_description: 'Respectfully submitting a civic grievance regarding critical tarmac damage and potholes on Anna Salai service lane (Thousand Lights constituency). This poses an active road safety hazard for two-wheelers and pedestrians. Requesting immediate patching and asphalt resurfacing.',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    constituency: 'Thousand Lights',
    locality: 'Anna Salai Service Lane, Near Thousand Lights Mosque',
    severity: 'HIGH',
    status: 'IN_PROGRESS',
    assigned_representative_id: 'rep-gcc-01',
    is_anonymous: false,
    submitter_name: 'Karthikeyan Ramasamy',
    submitter_email: 'karthik.r@example.com',
    submitter_phone: '9840123456',
    submitter_language: 'en',
    created_at: '2026-08-16T14:30:00Z',
    updated_at: '2026-08-17T09:15:00Z',
    updates: [
      {
        id: 'upd-01',
        complaint_id: 'complaint-sample-01',
        status: 'EMAIL_SENT',
        message: 'Official complaint dossier dispatched to Greater Chennai Corporation (GCC) Grievance Cell.',
        is_public: true,
        created_at: '2026-08-16T14:31:00Z',
      },
      {
        id: 'upd-02',
        complaint_id: 'complaint-sample-01',
        status: 'ACKNOWLEDGED',
        message: 'Zonal Executive Engineer (Zone 9) acknowledged receipt of complaint.',
        is_public: true,
        created_at: '2026-08-16T17:00:00Z',
      },
      {
        id: 'upd-03',
        complaint_id: 'complaint-sample-01',
        status: 'IN_PROGRESS',
        message: 'Road maintenance contractor scheduled asphalt cold-mix repair works.',
        is_public: true,
        created_at: '2026-08-17T09:15:00Z',
      },
    ],
    delivery_logs: [
      {
        id: 'del-01',
        complaint_id: 'complaint-sample-01',
        channel: 'EMAIL',
        recipient: 'commissioner@chennaicorporation.gov.in',
        status: 'SUCCESS',
        external_message_id: 'resend_msg_884920194',
        sent_at: '2026-08-16T14:31:00Z',
      },
    ],
  },
  {
    id: 'complaint-sample-02',
    reference_number: 'MK-2026-209144',
    category: 'water',
    subcategory: 'Pipeline Burst / Leakage',
    title: 'Drinking water pipe burst near Gandhipuram bus stand',
    description: 'Clean drinking water is overflowing on the main road for the past 2 days resulting in thousands of litres of water wastage and low water pressure for surrounding shops and households.',
    original_language: 'en',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    constituency: 'Coimbatore North',
    locality: 'Cross Cut Road, Gandhipuram',
    severity: 'HIGH',
    status: 'RESOLVED',
    assigned_representative_id: 'rep-ccmc-01',
    is_anonymous: false,
    submitter_name: 'Soundararajan V',
    submitter_email: 'soundar.cbe@example.com',
    submitter_phone: '9789012345',
    submitter_language: 'en',
    created_at: '2026-08-14T08:00:00Z',
    updated_at: '2026-08-15T16:00:00Z',
    updates: [
      {
        id: 'upd-201',
        complaint_id: 'complaint-sample-02',
        status: 'EMAIL_SENT',
        message: 'Dispatched to Coimbatore City Municipal Corporation water works division.',
        is_public: true,
        created_at: '2026-08-14T08:02:00Z',
      },
      {
        id: 'upd-202',
        complaint_id: 'complaint-sample-02',
        status: 'RESOLVED',
        message: 'Municipal engineering team replaced faulty pipe valve section. Water supply fully restored.',
        is_public: true,
        created_at: '2026-08-15T16:00:00Z',
      }
    ],
  },
  {
    id: 'complaint-sample-03',
    reference_number: 'MK-2026-319082',
    category: 'electricity',
    subcategory: 'Dangerous Hanging Cables',
    title: 'Low hanging high-tension electric wire near Government High School',
    description: 'Due to recent wind and heavy rains, the overhead wire has loosened and is hanging dangerously low (around 7 feet above road level) right in front of the school gate.',
    original_language: 'en',
    state: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Madurai',
    constituency: 'Madurai Central',
    locality: 'Simmakkal North Street',
    severity: 'URGENT',
    status: 'ACTION_TAKEN' as any,
    assigned_representative_id: 'rep-madurai-01',
    is_anonymous: false,
    submitter_name: 'Meenakshi Sundaram',
    submitter_email: 'meenakshi.mdu@example.com',
    submitter_phone: '9443012345',
    submitter_language: 'en',
    created_at: '2026-08-17T11:00:00Z',
    updated_at: '2026-08-17T13:45:00Z',
    updates: [
      {
        id: 'upd-301',
        complaint_id: 'complaint-sample-03',
        status: 'EMAIL_SENT',
        message: 'Priority urgent alert dispatched to TANGEDCO Madurai Central Division.',
        is_public: true,
        created_at: '2026-08-17T11:02:00Z',
      },
      {
        id: 'upd-302',
        complaint_id: 'complaint-sample-03',
        status: 'IN_PROGRESS',
        message: 'Emergency lineman crew dispatched to secure and tighten the line.',
        is_public: true,
        created_at: '2026-08-17T13:45:00Z',
      }
    ],
  }
];

// In-Memory & Local Storage Store Singleton for SSR/CSR
class MockDataStore {
  private complaints: Complaint[] = [...INITIAL_COMPLAINTS];
  private representatives: Representative[] = [...INITIAL_REPRESENTATIVES];

  constructor() {
    if (typeof window !== 'undefined') {
      const storedComplaints = localStorage.getItem('mk_complaints');
      if (storedComplaints) {
        try {
          this.complaints = JSON.parse(storedComplaints);
        } catch {
          // fallback to defaults
        }
      }
      const storedReps = localStorage.getItem('mk_representatives');
      if (storedReps) {
        try {
          this.representatives = JSON.parse(storedReps);
        } catch {
          // fallback to defaults
        }
      }
    }
  }

  private persist() {
    if (typeof window !== 'undefined') {
      localStorage.setItem('mk_complaints', JSON.stringify(this.complaints));
      localStorage.setItem('mk_representatives', JSON.stringify(this.representatives));
    }
  }

  public getComplaints(): Complaint[] {
    return this.complaints;
  }

  public getComplaintByReference(ref: string): Complaint | undefined {
    return this.complaints.find(c => c.reference_number.toUpperCase() === ref.trim().toUpperCase());
  }

  public getComplaintById(id: string): Complaint | undefined {
    return this.complaints.find(c => c.id === id);
  }

  public addComplaint(complaint: Complaint): Complaint {
    this.complaints.unshift(complaint);
    this.persist();
    return complaint;
  }

  public updateComplaintStatus(
    id: string, 
    status: any, 
    publicMessage?: string, 
    assignedRepId?: string
  ): Complaint | null {
    const complaint = this.complaints.find(c => c.id === id);
    if (!complaint) return null;

    complaint.status = status;
    complaint.updated_at = new Date().toISOString();
    if (assignedRepId) {
      complaint.assigned_representative_id = assignedRepId;
    }

    if (publicMessage) {
      if (!complaint.updates) complaint.updates = [];
      complaint.updates.unshift({
        id: 'upd-' + Date.now(),
        complaint_id: id,
        status,
        message: publicMessage,
        is_public: true,
        created_at: new Date().toISOString(),
      });
    }

    this.persist();
    return complaint;
  }

  public getRepresentatives(): Representative[] {
    return this.representatives;
  }

  public getRepresentativeById(id: string): Representative | undefined {
    return this.representatives.find(r => r.id === id);
  }

  public addRepresentative(rep: Representative): Representative {
    this.representatives.unshift(rep);
    this.persist();
    return rep;
  }

  public updateRepresentative(id: string, updates: Partial<Representative>): Representative | null {
    const rep = this.representatives.find(r => r.id === id);
    if (!rep) return null;
    Object.assign(rep, updates, { updated_at: new Date().toISOString() });
    this.persist();
    return rep;
  }
}

export const mockStore = new MockDataStore();
