import { Complaint, Representative, DeliveryLog, ComplaintUpdate } from '@/types/database';

export const INITIAL_REPRESENTATIVES: Representative[] = [
  {
    id: 'rep-gcc-01',
    name: 'Commissioner Office, Greater Chennai Corporation',
    role: 'Commissioner / Grievance Cell',
    organization: 'Greater Chennai Corporation (GCC)',
    category_specialty: 'Garbage, Roads, Drainage, Street Lights',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'commissioner@chennaicorporation.gov.in',
    x_handle: 'chennaicorp',
    official_website: 'https://chennaicorporation.gov.in',
    source_url: 'https://erp.chennaicorporation.gov.in/pgr/',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rep-tneb-01',
    name: 'Chief Engineer (Distribution) - Chennai South',
    role: 'Chief Distribution Engineer',
    organization: 'TANGEDCO (Tamil Nadu Electricity Board)',
    category_specialty: 'Electricity',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'Mylapore, Velachery, T.Nagar, Sholinganallur',
    email: 'cedsouth@tnebnet.org',
    x_handle: 'TANGEDCO_Offcl',
    official_website: 'https://www.tnpdcl.org',
    source_url: 'https://www.tnpdcl.org/en/tnpdcl/reach-us/contact-information/',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rep-cmwssb-01',
    name: 'Chennai Metro Water - Operations Department',
    role: 'Executive Director (Water Supply & Sewerage)',
    organization: 'Chennai Metropolitan Water Supply and Sewerage Board (CMWSSB)',
    category_specialty: 'Water, Drainage',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'cmwssb@tn.gov.in',
    x_handle: 'CMWSSB_Official',
    official_website: 'https://cmwssb.tn.gov.in',
    source_url: 'https://cmwssb.tn.gov.in/complaints',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'rep-ccmc-01',
    name: 'Commissioner, Coimbatore City Municipal Corporation',
    role: 'Municipal Commissioner',
    organization: 'Coimbatore City Municipal Corporation',
    category_specialty: 'Roads, Water, Garbage, Drainage',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    constituency: 'Coimbatore South, Coimbatore North, Singanallur',
    email: 'commr.coimbatore@tn.gov.in',
    x_handle: 'CbeCityCorp',
    official_website: 'https://ccmc.gov.in',
    source_url: 'https://ccmc.gov.in/index.php/contact-us',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-05T11:30:00Z',
  },
  {
    id: 'rep-madurai-01',
    name: 'Commissioner, Madurai Municipal Corporation',
    role: 'Corporation Commissioner',
    organization: 'Madurai Municipal Corporation',
    category_specialty: 'Roads, Drainage, Water, Healthcare',
    state: 'Tamil Nadu',
    district: 'Madurai',
    constituency: 'Madurai North, Madurai South, Madurai Central, Madurai West',
    email: 'commr.madurai@tn.gov.in',
    x_handle: 'MaduraiCorp',
    official_website: 'https://www.maduraicorporation.co.in',
    source_url: 'https://maduraicorporation.co.in/contact-us/',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-10T09:00:00Z',
  },
  {
    id: 'rep-trichy-01',
    name: 'Commissioner, Tiruchirappalli City Corporation',
    role: 'Corporation Commissioner',
    organization: 'Tiruchirappalli City Corporation',
    category_specialty: 'Roads, Water, Garbage, Public Safety',
    state: 'Tamil Nadu',
    district: 'Tiruchirappalli',
    constituency: 'Tiruchirappalli West, Tiruchirappalli East, Srirangam',
    email: 'commr.trichy@tn.gov.in',
    x_handle: 'TrichyCorp',
    official_website: 'https://www.trichycorporation.gov.in',
    source_url: 'https://www.trichycorporation.gov.in/contact',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-12T14:20:00Z',
  },
  {
    id: 'rep-salem-01',
    name: 'Commissioner, Salem City Municipal Corporation',
    role: 'Municipal Commissioner',
    organization: 'Salem City Municipal Corporation',
    category_specialty: 'Roads, Drainage, Street Lights, Garbage',
    state: 'Tamil Nadu',
    district: 'Salem',
    constituency: 'Salem North, Salem South, Salem West',
    email: 'commr.salem@tn.gov.in',
    x_handle: 'SalemCorp',
    official_website: 'https://www.salemcorporation.gov.in',
    source_url: 'https://www.salemcorporation.gov.in/contact.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-14T10:00:00Z',
  },
  {
    id: 'rep-tirunelveli-01',
    name: 'Commissioner, Tirunelveli City Municipal Corporation',
    role: 'Municipal Commissioner',
    organization: 'Tirunelveli Corporation',
    category_specialty: 'Roads, Water, Sanitation, Transport',
    state: 'Tamil Nadu',
    district: 'Tirunelveli',
    constituency: 'Tirunelveli, Palayamkottai',
    email: 'commr.tirunelveli@tn.gov.in',
    x_handle: 'TirunelveliCorp',
    official_website: 'https://www.tirunelvelicorporation.com',
    source_url: 'https://www.tirunelvelicorporation.com/contact-us',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-07-25T12:00:00Z',
  },
  {
    id: 'rep-kanchi-01',
    name: 'District Collector & Magistrate, Kanchipuram',
    role: 'District Collector',
    organization: 'Kanchipuram District Administration',
    category_specialty: 'Government Services, Transport, Environment',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    constituency: 'Kanchipuram, Sriperumbudur, Uthiramerur',
    email: 'collr-knc@nic.in',
    x_handle: 'KanchiCollector',
    official_website: 'https://kancheepuram.nic.in',
    source_url: 'https://kancheepuram.nic.in/citizen-charter',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-15T08:30:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-15T08:30:00Z',
  },
  {
    id: 'rep-thanjavur-01',
    name: 'District Collector, Thanjavur',
    role: 'District Collector',
    organization: 'Thanjavur District Administration',
    category_specialty: 'Water, Agriculture, Roads',
    state: 'Tamil Nadu',
    district: 'Thanjavur',
    constituency: 'Thanjavur, Kumbakonam, Papanasam, Orathanadu',
    email: 'collr-tj@nic.in',
    x_handle: 'TnjCollector',
    official_website: 'https://thanjavur.nic.in',
    source_url: 'https://thanjavur.nic.in/departments',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-07-30T11:00:00Z',
  },
  {
    id: 'rep-collector-erode-01',
    name: 'District Collector & Magistrate, Erode',
    role: 'District Collector',
    organization: 'Erode District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Erode',
    constituency: 'Erode East, Erode West, Modakkurichi, Perundurai, Bhavani',
    email: 'collr-erode@nic.in',
    x_handle: 'ErodeCollector',
    official_website: 'https://erode.nic.in',
    source_url: 'https://erode.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tiruppur-01',
    name: 'District Collector & Magistrate, Tiruppur',
    role: 'District Collector',
    organization: 'Tiruppur District Administration',
    category_specialty: 'Textiles, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    constituency: 'Tiruppur North, Tiruppur South, Palladam, Udumalaipettai',
    email: 'collr-tiruppur@nic.in',
    x_handle: 'TiruppurCollector',
    official_website: 'https://tiruppur.nic.in',
    source_url: 'https://tiruppur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-vellore-01',
    name: 'District Collector & Magistrate, Vellore',
    role: 'District Collector',
    organization: 'Vellore District Administration',
    category_specialty: 'Healthcare, Education, Public Services',
    state: 'Tamil Nadu',
    district: 'Vellore',
    constituency: 'Vellore, Anaikattu, Kilvaithinankuppam, Gudiyattam',
    email: 'collr-vellore@nic.in',
    x_handle: 'VelloreCollector',
    official_website: 'https://vellore.nic.in',
    source_url: 'https://vellore.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-dindigul-01',
    name: 'District Collector & Magistrate, Dindigul',
    role: 'District Collector',
    organization: 'Dindigul District Administration',
    category_specialty: 'Agriculture, Tourism, Public Services',
    state: 'Tamil Nadu',
    district: 'Dindigul',
    constituency: 'Dindigul, Palani, Oddanchatram, Athoor, Nilakkottai',
    email: 'collr-dindigul@nic.in',
    x_handle: 'DindigulCollector',
    official_website: 'https://dindigul.nic.in',
    source_url: 'https://dindigul.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-cuddalore-01',
    name: 'District Collector & Magistrate, Cuddalore',
    role: 'District Collector',
    organization: 'Cuddalore District Administration',
    category_specialty: 'Ports, Industries, Agriculture',
    state: 'Tamil Nadu',
    district: 'Cuddalore',
    constituency: 'Cuddalore, Panruti, Chidambaram, Kattumannarkoil',
    email: 'collr-cuddalore@nic.in',
    x_handle: 'CuddaloreCollector',
    official_website: 'https://cuddalore.nic.in',
    source_url: 'https://cuddalore.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-thoothukudi-01',
    name: 'District Collector & Magistrate, Thoothukudi',
    role: 'District Collector',
    organization: 'Thoothukudi District Administration',
    category_specialty: 'Ports, Shipping, Salt',
    state: 'Tamil Nadu',
    district: 'Thoothukudi',
    constituency: 'Thoothukudi, Tiruchendur, Srivaikuntam, Ottapidaram',
    email: 'collr-thoothukudi@nic.in',
    x_handle: 'ThoothukudiCollector',
    official_website: 'https://thoothukudi.nic.in',
    source_url: 'https://thoothukudi.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-kanyakumari-01',
    name: 'District Collector & Magistrate, Kanyakumari',
    role: 'District Collector',
    organization: 'Kanyakumari District Administration',
    category_specialty: 'Tourism, Fisheries, Public Services',
    state: 'Tamil Nadu',
    district: 'Kanyakumari',
    constituency: 'Kanyakumari, Nagercoil, Colachel, Padmanabhapuram',
    email: 'collr-kanyakumari@nic.in',
    x_handle: 'KanyakumariCollector',
    official_website: 'https://kanyakumari.nic.in',
    source_url: 'https://kanyakumari.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-dharmapuri-01',
    name: 'District Collector & Magistrate, Dharmapuri',
    role: 'District Collector',
    organization: 'Dharmapuri District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri, Palacodu, Pennagaram, Harur',
    email: 'collr-dharmapuri@nic.in',
    x_handle: 'DharmapuriCollector',
    official_website: 'https://dharmapuri.nic.in',
    source_url: 'https://dharmapuri.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-krishnagiri-01',
    name: 'District Collector & Magistrate, Krishnagiri',
    role: 'District Collector',
    organization: 'Krishnagiri District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    constituency: 'Krishnagiri, Hosur, Uthangarai, Bargur',
    email: 'collr-krishnagiri@nic.in',
    x_handle: 'KrishnagiriCollector',
    official_website: 'https://krishnagiri.nic.in',
    source_url: 'https://krishnagiri.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-namakkal-01',
    name: 'District Collector & Magistrate, Namakkal',
    role: 'District Collector',
    organization: 'Namakkal District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Namakkal',
    constituency: 'Namakkal, Rasipuram, Senthamangalam, Paramathi-Velur',
    email: 'collr-namakkal@nic.in',
    x_handle: 'NamakkalCollector',
    official_website: 'https://namakkal.nic.in',
    source_url: 'https://namakkal.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-villupuram-01',
    name: 'District Collector & Magistrate, Villupuram',
    role: 'District Collector',
    organization: 'Villupuram District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Villupuram',
    constituency: 'Villupuram, Vikravandi, Tindivanam, Vanur',
    email: 'collr-villupuram@nic.in',
    x_handle: 'VillupuramCollector',
    official_website: 'https://villupuram.nic.in',
    source_url: 'https://villupuram.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-nagapattinam-01',
    name: 'District Collector & Magistrate, Nagapattinam',
    role: 'District Collector',
    organization: 'Nagapattinam District Administration',
    category_specialty: 'Fisheries, Ports, Public Services',
    state: 'Tamil Nadu',
    district: 'Nagapattinam',
    constituency: 'Nagapattinam, Kilvelur, Vedaranyam',
    email: 'collr-nagapattinam@nic.in',
    x_handle: 'NagapattinamCollector',
    official_website: 'https://nagapattinam.nic.in',
    source_url: 'https://nagapattinam.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-pudukkottai-01',
    name: 'District Collector & Magistrate, Pudukkottai',
    role: 'District Collector',
    organization: 'Pudukkottai District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Pudukkottai',
    constituency: 'Pudukkottai, Gandarvakottai, Viralimalai, Thirumayam',
    email: 'collr-pudukkottai@nic.in',
    x_handle: 'PudukkottaiCollector',
    official_website: 'https://pudukkottai.nic.in',
    source_url: 'https://pudukkottai.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-ramanathapuram-01',
    name: 'District Collector & Magistrate, Ramanathapuram',
    role: 'District Collector',
    organization: 'Ramanathapuram District Administration',
    category_specialty: 'Fisheries, Pilgrimage, Public Services',
    state: 'Tamil Nadu',
    district: 'Ramanathapuram',
    constituency: 'Ramanathapuram, Paramakudi, Tiruvadanai, Mudukulathur',
    email: 'collr-ramanathapuram@nic.in',
    x_handle: 'RamanathapuramCollector',
    official_website: 'https://ramanathapuram.nic.in',
    source_url: 'https://ramanathapuram.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-virudhunagar-01',
    name: 'District Collector & Magistrate, Virudhunagar',
    role: 'District Collector',
    organization: 'Virudhunagar District Administration',
    category_specialty: 'Industries, Commerce, Public Services',
    state: 'Tamil Nadu',
    district: 'Virudhunagar',
    constituency: 'Virudhunagar, Sivakasi, Sattur, Aruppukkottai',
    email: 'collr-virudhunagar@nic.in',
    x_handle: 'VirudhunagarCollector',
    official_website: 'https://virudhunagar.nic.in',
    source_url: 'https://virudhunagar.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-sivaganga-01',
    name: 'District Collector & Magistrate, Sivaganga',
    role: 'District Collector',
    organization: 'Sivaganga District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Sivaganga',
    constituency: 'Sivaganga, Karaikudi, Tiruppattur, Manamadurai',
    email: 'collr-sivaganga@nic.in',
    x_handle: 'SivagangaCollector',
    official_website: 'https://sivaganga.nic.in',
    source_url: 'https://sivaganga.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-nilgiris-01',
    name: 'District Collector & Magistrate, The Nilgiris',
    role: 'District Collector',
    organization: 'The Nilgiris District Administration',
    category_specialty: 'Tourism, Environment, Public Services',
    state: 'Tamil Nadu',
    district: 'Nilgiris',
    constituency: 'Udhagamandalam, Coonoor, Gudalur',
    email: 'collr-nilgiris@nic.in',
    x_handle: 'NilgirisCollector',
    official_website: 'https://nilgiris.nic.in',
    source_url: 'https://nilgiris.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-theeni-01',
    name: 'District Collector & Magistrate, Theni',
    role: 'District Collector',
    organization: 'Theni District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Theni',
    constituency: 'Bodinayakanur, Periyakulam, Cumbum, Andipatti',
    email: 'collr-theni@nic.in',
    x_handle: 'TheniCollector',
    official_website: 'https://theni.nic.in',
    source_url: 'https://theni.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-karur-01',
    name: 'District Collector & Magistrate, Karur',
    role: 'District Collector',
    organization: 'Karur District Administration',
    category_specialty: 'Textiles, Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Karur',
    constituency: 'Karur, Aravakurichi, Krishnarayapuram, Kulithalai',
    email: 'collr-karur@nic.in',
    x_handle: 'KarurCollector',
    official_website: 'https://karur.nic.in',
    source_url: 'https://karur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-perambalur-01',
    name: 'District Collector & Magistrate, Perambalur',
    role: 'District Collector',
    organization: 'Perambalur District Administration',
    category_specialty: 'Agriculture, Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Perambalur',
    constituency: 'Perambalur, Kunnam',
    email: 'collr-perambalur@nic.in',
    x_handle: 'PerambalurCollector',
    official_website: 'https://perambalur.nic.in',
    source_url: 'https://perambalur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-ariyalur-01',
    name: 'District Collector & Magistrate, Ariyalur',
    role: 'District Collector',
    organization: 'Ariyalur District Administration',
    category_specialty: 'Cement, Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Ariyalur',
    constituency: 'Ariyalur, Jayankondam',
    email: 'collr-ariyalur@nic.in',
    x_handle: 'AriyalurCollector',
    official_website: 'https://ariyalur.nic.in',
    source_url: 'https://ariyalur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-thiruvarur-01',
    name: 'District Collector & Magistrate, Thiruvarur',
    role: 'District Collector',
    organization: 'Thiruvarur District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Thiruvarur',
    constituency: 'Thiruvarur, Mannargudi, Thiruthuraipoondi, Nannilam',
    email: 'collr-thiruvarur@nic.in',
    x_handle: 'ThiruvarurCollector',
    official_website: 'https://thiruvarur.nic.in',
    source_url: 'https://thiruvarur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tiruvannamalai-01',
    name: 'District Collector & Magistrate, Tiruvannamalai',
    role: 'District Collector',
    organization: 'Tiruvannamalai District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Tiruvannamalai',
    constituency: 'Tiruvannamalai, Chengam, Polur, Arani',
    email: 'collr-tiruvannamalai@nic.in',
    x_handle: 'TiruvannamalaiCollector',
    official_website: 'https://tiruvannamalai.nic.in',
    source_url: 'https://tiruvannamalai.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-ranipet-01',
    name: 'District Collector & Magistrate, Ranipet',
    role: 'District Collector',
    organization: 'Ranipet District Administration',
    category_specialty: 'Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Ranipet',
    constituency: 'Ranipet, Arcot, Sholinghur, Arakkonam',
    email: 'collr-ranipet@nic.in',
    x_handle: 'RanipetCollector',
    official_website: 'https://ranipet.nic.in',
    source_url: 'https://ranipet.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tirupathur-01',
    name: 'District Collector & Magistrate, Tirupathur',
    role: 'District Collector',
    organization: 'Tirupathur District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Tirupathur',
    constituency: 'Tirupathur, Vaniyambadi, Ambur, Jolarpet',
    email: 'collr-tirupathur@nic.in',
    x_handle: 'TirupathurCollector',
    official_website: 'https://tirupathur.nic.in',
    source_url: 'https://tirupathur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-kallakurichi-01',
    name: 'District Collector & Magistrate, Kallakurichi',
    role: 'District Collector',
    organization: 'Kallakurichi District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Kallakurichi',
    constituency: 'Kallakurichi, Rishivandiyam, Sankarapuram, Ulundurpet',
    email: 'collr-kallakurichi@nic.in',
    x_handle: 'KallakurichiCollector',
    official_website: 'https://kallakurichi.nic.in',
    source_url: 'https://kallakurichi.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-tenkasi-01',
    name: 'District Collector & Magistrate, Tenkasi',
    role: 'District Collector',
    organization: 'Tenkasi District Administration',
    category_specialty: 'Agriculture, Tourism, Public Services',
    state: 'Tamil Nadu',
    district: 'Tenkasi',
    constituency: 'Tenkasi, Kadayanallur, Vasudevanallur, Sankarankovil',
    email: 'collr-tenkasi@nic.in',
    x_handle: 'TenkasiCollector',
    official_website: 'https://tenkasi.nic.in',
    source_url: 'https://tenkasi.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-collector-mayiladuthurai-01',
    name: 'District Collector & Magistrate, Mayiladuthurai',
    role: 'District Collector',
    organization: 'Mayiladuthurai District Administration',
    category_specialty: 'Agriculture, Public Services',
    state: 'Tamil Nadu',
    district: 'Mayiladuthurai',
    constituency: 'Mayiladuthurai, Sirkazhi, Poompuhar',
    email: 'collr-mayiladuthurai@nic.in',
    x_handle: 'MayiladuthuraiCollector',
    official_website: 'https://mayiladuthurai.nic.in',
    source_url: 'https://mayiladuthurai.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-chengalpattu-01',
    name: 'District Collector & Magistrate, Chengalpattu',
    role: 'District Collector',
    organization: 'Chengalpattu District Administration',
    category_specialty: 'Industries, IT, Public Services',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    constituency: 'Chengalpattu, Tambaram, Pallavaram, Madurantakam',
    email: 'collr-chengalpattu@nic.in',
    x_handle: 'ChengalpattuCollector',
    official_website: 'https://chengalpattu.nic.in',
    source_url: 'https://chengalpattu.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: 'rep-thiruvallur-01',
    name: 'District Collector & Magistrate, Thiruvallur',
    role: 'District Collector',
    organization: 'Thiruvallur District Administration',
    category_specialty: 'Industries, Public Services',
    state: 'Tamil Nadu',
    district: 'Thiruvallur',
    constituency: 'Thiruvallur, Avadi, Poonamallee, Ambattur',
    email: 'collr-thiruvallur@nic.in',
    x_handle: 'ThiruvallurCollector',
    official_website: 'https://thiruvallur.nic.in',
    source_url: 'https://thiruvallur.nic.in',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-22T18:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-22T18:00:00Z',
  },
  {
    id: '69e8ac91-a5ab-48ae-ab7f-ec677ce3bb82',
    name: 'Hon\'ble Chief Minister C. Joseph Vijay',
    role: 'Chief Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Public, Home, General Administration, Municipal Administration, Urban and Water Supply, Police, IAS, IPS, IFS, Special Programme Implementation, Poverty Alleviation, Youth Welfare, Welfare of Children, Aged, Differently Abled Persons',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'cmo@tn.gov.in',
    x_handle: 'CMOTamilNadu',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '29154109-2819-48f2-9715-529bd5a6d94b',
    name: 'Hon\'ble Minister N. Anand',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Rural Development, Panchayats, Rural Indebtedness, Irrigation, Water Resources, Small Irrigation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_wrd@tn.gov.in',
    x_handle: 'TNRuralDevMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '42d46043-82b9-43c4-afa6-70d65a46c37b',
    name: 'Hon\'ble Minister Aadhav Arjuna',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Public Works, Buildings, Highways, Minor Ports, Sports Development',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_pwd@tn.gov.in',
    x_handle: 'TNPWDMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'f72eeaca-58e2-4025-b38d-32ddc6d1d739',
    name: 'Hon\'ble Minister Dr. K.G. Arunraj',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Health, Medical Education, Family Welfare, Hospitals, Public Health',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_health@tn.gov.in',
    x_handle: 'TNHealthMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '63998466-4e30-4a31-af06-7008dbc569a7',
    name: 'Hon\'ble Minister K.A. Sengottaiyan',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Revenue, Disaster Management, Relief, Land Records, Registration',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_revenue@tn.gov.in',
    x_handle: 'TNRevenueMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '57696daa-514b-4686-8687-4c29ecd0e2cf',
    name: 'Hon\'ble Minister P. Venkataramanan',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Food and Civil Supplies, Consumer Protection, Price Control, Ration Shops',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_food@tn.gov.in',
    x_handle: 'TNFoodMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'd973af9e-c727-499b-8dc8-283cfc27138e',
    name: 'Hon\'ble Minister R. Nirmalkumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Energy Resources, Electricity, Law, Courts, Prisons, Prevention of Corruption',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_energy@tn.gov.in',
    x_handle: 'TNEnergyMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'ee2b9331-785b-4387-b9d6-87e15c6afad0',
    name: 'Hon\'ble Minister Rajmohan',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'School Education, Tamil Development, Information and Publicity, Film Technology, Newsprint Control',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_schedu@tn.gov.in',
    x_handle: 'TNSchoolEduMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'db10f799-b75c-4ce6-8ae1-424b5fb702ba',
    name: 'Hon\'ble Minister T.K. Prabhu',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Natural Resources, Minerals, Mines, Geology',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_natural@tn.gov.in',
    x_handle: 'TNNaturalResMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'b43ee7e0-2e7c-48a6-a549-a124d3e83d48',
    name: 'Hon\'ble Minister Dr. T.R.B. Rajaa',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Industries, Investment Promotion, Manufacturing, Industrial Estates',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_industry@tn.gov.in',
    x_handle: 'TNIndustryMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '9d8e5ae3-3c8e-43c8-8fc8-6dd2feacf110',
    name: 'Hon\'ble Minister P. Viswanathan',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Higher Education, Technical Education, Electronics, Science and Technology, Research',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_hredu@tn.gov.in',
    x_handle: 'TNHigherEduMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'e1afdb53-a71d-48f1-b8f5-bf064a95a692',
    name: 'Hon\'ble Minister S. Rajesh Kumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Tourism, Tourism Development Corporation, Heritage, Pilgrimage',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_tourism@tn.gov.in',
    x_handle: 'TNTourismMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '80a19d9a-dadf-46b5-b57d-1695b10255f7',
    name: 'Hon\'ble Minister A.M. Shahjahan',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Minorities Welfare, Wakf Board, Minority Education, Urdu',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_mw@tn.gov.in',
    x_handle: 'TNMinorityMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'a4a0149b-ec97-438b-bb0a-afaa96f3903d',
    name: 'Hon\'ble Minister Vanni Arasu',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Social Justice, Adi Dravidar Welfare, Hill Tribes, SC/ST Welfare',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_sj@tn.gov.in',
    x_handle: 'TNSocialJusticeMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '530f81fb-842b-472a-928a-47b72b70e3ae',
    name: 'Hon\'ble Minister A. Vijay Tamilan Parthiban',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Transport, Motor Vehicles, National Highways, Road Transport, Public Transport',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_transport@tn.gov.in',
    x_handle: 'TNTransportMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'd2ba57fb-f051-4657-9a2a-231226abfb1b',
    name: 'Hon\'ble Minister B. Rajkumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Housing, Urban Development, Town Planning, Slum Clearance',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_housing@tn.gov.in',
    x_handle: 'TNHousingMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '196069b4-f6f8-4f6e-a6d5-074159f1445f',
    name: 'Hon\'ble Minister V. Sampath Kumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Backward Classes Welfare, Most Backward Classes, De-notified Communities, Reservation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_bcmw@tn.gov.in',
    x_handle: 'TNBCMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '0ebd3087-ad0a-4d76-bc8c-2cbb0fd401e9',
    name: 'Hon\'ble Minister M. Vijay Balaji',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Handlooms, Textiles, Khadi, Handicrafts, Silk',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_textiles@tn.gov.in',
    x_handle: 'TNTextilesMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'd70d963e-e57a-40e4-8f55-917e0c6b8326',
    name: 'Hon\'ble Minister K. Vignesh',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Prohibition, Excise, Liquor Control, Narcotics',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_excise@tn.gov.in',
    x_handle: 'TNProhibitionMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '16c9193b-f478-4933-99c3-5bd931819d08',
    name: 'Hon\'ble Minister K. Thennarasu',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Non-Resident Tamils Welfare, Overseas Indians, Emigration',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_nrt@tn.gov.in',
    x_handle: 'TN_NRTMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '7bfb04bc-6b82-4755-95b7-71e9eeb2b396',
    name: 'Hon\'ble Minister J. Mohamed Farvas',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Labour Welfare, Skill Development, Employment, Industrial Training, Workers Rights',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_labour@tn.gov.in',
    x_handle: 'TNLabourMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '0cde03c1-f5aa-4e2b-821b-e8e11c870424',
    name: 'Hon\'ble Minister V. Gandhiraj',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Co-operation, Cooperative Societies, Cooperative Banks',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_coop@tn.gov.in',
    x_handle: 'TNCoopMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '6d9b2d80-9f5c-4418-88a9-68fc183267f1',
    name: 'Hon\'ble Minister Jagadeshwari K.',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Social Welfare, Women Empowerment, Child Welfare, Orphanages, Destitutes',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_sw@tn.gov.in',
    x_handle: 'TNSocialWelfareMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '5db643bc-72bc-4843-977a-580b458f37c4',
    name: 'Hon\'ble Minister R. Vinoth',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Agriculture, Farmers Welfare, Crop Insurance, Agricultural Marketing',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_agri@tn.gov.in',
    x_handle: 'TNAgriMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '54f3ac61-e829-4de0-9451-88f05b7b7e86',
    name: 'Hon\'ble Minister C. Vijayalakshmi',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Milk and Dairy Development, Dairy Cooperatives, Animal Products',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_mdd@tn.gov.in',
    x_handle: 'TNDairyMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'a7fbeec8-a206-498c-9f5f-67f0990d015f',
    name: 'Hon\'ble Minister D. Sarathkumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Human Resources Management, Ex-Servicemen Welfare, Pension',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_hr@tn.gov.in',
    x_handle: 'TNHRMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '61c833f2-cbc0-4a90-8973-989e9dd492ca',
    name: 'Hon\'ble Minister Ramesh',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Hindu Religious and Charitable Endowments, Temples, Religious Institutions',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_hrce@tn.gov.in',
    x_handle: 'TNHRCEMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'e91ace03-fbde-456d-9e49-9e101e7092cf',
    name: 'Hon\'ble Minister P. Mathan Raja',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Micro, Small and Medium Enterprises, MSME, Entrepreneurship, Startups',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_msme@tn.gov.in',
    x_handle: 'TNMSMEMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: '68aa13bf-79b5-4500-9dfd-aac08429fde7',
    name: 'Hon\'ble Minister N. Marie Wilson',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Finance, Planning and Development, Budget, Treasury, Economics',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_finance@tn.gov.in',
    x_handle: 'TNFinanceMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'a626e3a1-f26c-4a3e-87a6-d2b6d11d33eb',
    name: 'Hon\'ble Minister A. Srinath',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Fisheries, Fishermen Welfare, Aquaculture, Fishing Harbours',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_fisheries@tn.gov.in',
    x_handle: 'TNFisheriesMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'd69cb7d5-35fe-491b-9937-792a06c75579',
    name: 'Hon\'ble Minister S. Kamali',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Animal Husbandry, Veterinary Services, Livestock, Poultry',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_ah@tn.gov.in',
    x_handle: 'TNAHMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'e7ab641b-adc5-4202-97fe-e93128bc7286',
    name: 'Hon\'ble Minister R. Kumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Artificial Intelligence, IT and Digital Services, Electronics, E-Governance, Technology',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_it@tn.gov.in',
    x_handle: 'TNITMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'f8f13ba3-e98d-4d57-8937-cbb6d0839bcf',
    name: 'Hon\'ble Minister R.V. Ranjithkumar',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Forests, Wildlife, Environment, Afforestation, Forest Conservation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_forests@tn.gov.in',
    x_handle: 'TNForestMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'd6b67552-f8b4-46f6-bbd7-fb7c6a40a84a',
    name: 'Hon\'ble Minister D. Logesh Tamilselvan',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Commercial Taxes and Registration, GST, Stamp Duty, Registration',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_ctax@tn.gov.in',
    x_handle: 'TNCTaxMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
  {
    id: 'cac3e4cb-2638-41e3-93d2-058f0f32ad96',
    name: 'Hon\'ble Minister V.K. Rajeev',
    role: 'Cabinet Minister',
    organization: 'Government of Tamil Nadu',
    category_specialty: 'Environment and Climate Change, Pollution Control, Climate Action',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'All Constituencies',
    email: 'minister_env@tn.gov.in',
    x_handle: 'TNEnvMin',
    official_website: 'https://www.tn.gov.in',
    source_url: 'https://www.tn.gov.in/minister_list.php',
    verification_status: 'VERIFIED',
    last_verified_at: '2026-08-23T06:00:00Z',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-08-23T06:00:00Z',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'complaint-sample-01',
    reference_number: 'MK-2026-104829',
    category: 'roads',
    subcategory: 'Potholes',
    title: 'Severe crater potholes on Anna Salai service lane near Thousand Lights',
    description: 'Multiple deep potholes have formed on the service lane causing severe traffic slowdowns and motorbike skidding accidents during evening peak hours.',
    original_language: 'en',
    ai_improved_title: 'Urgent Road Repair Request: Pothole Hazards on Anna Salai Service Road',
    ai_improved_description: 'Respectfully submitting a civic grievance regarding critical tarmac damage and potholes on Anna Salai service lane (Thousand Lights constituency). This poses an active road safety hazard for two-wheelers and pedestrians. Requesting immediate patching and asphalt resurfacing.',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    constituency: 'Thousand Lights',
    locality: 'Anna Salai Service Lane, Near Thousand Lights Mosque',
    latitude: 13.0569,
    longitude: 80.2525,
    severity: 'HIGH',
    status: 'IN_PROGRESS',
    assigned_representative_id: 'rep-gcc-01',
    is_anonymous: false,
    submitter_name: 'Karthikeyan Ramasamy',
    submitter_email: 'karthik.r@example.com',
    submitter_phone: '9840123456',
    submitter_language: 'en',
    created_at: '2026-08-16T14:30:00Z',
    updated_at: '2026-08-17T09:15:00Z',
    updates: [
      {
        id: 'upd-01',
        complaint_id: 'complaint-sample-01',
        status: 'EMAIL_SENT',
        message: 'Official complaint dossier dispatched to Greater Chennai Corporation (GCC) Grievance Cell.',
        is_public: true,
        created_at: '2026-08-16T14:31:00Z',
      },
      {
        id: 'upd-02',
        complaint_id: 'complaint-sample-01',
        status: 'ACKNOWLEDGED',
        message: 'Zonal Executive Engineer (Zone 9) acknowledged receipt of complaint.',
        is_public: true,
        created_at: '2026-08-16T17:00:00Z',
      },
      {
        id: 'upd-03',
        complaint_id: 'complaint-sample-01',
        status: 'IN_PROGRESS',
        message: 'Road maintenance contractor scheduled asphalt cold-mix repair works.',
        is_public: true,
        created_at: '2026-08-17T09:15:00Z',
      },
    ],
    delivery_logs: [
      {
        id: 'del-01',
        complaint_id: 'complaint-sample-01',
        channel: 'EMAIL',
        recipient: 'commissioner@chennaicorporation.gov.in',
        status: 'SUCCESS',
        external_message_id: 'resend_msg_884920194',
        sent_at: '2026-08-16T14:31:00Z',
      },
    ],
  },
  {
    id: 'complaint-sample-02',
    reference_number: 'MK-2026-209144',
    category: 'water',
    subcategory: 'Pipeline Burst / Leakage',
    title: 'Drinking water pipe burst near Gandhipuram bus stand',
    description: 'Clean drinking water is overflowing on the main road for the past 2 days resulting in thousands of litres of water wastage and low water pressure for surrounding shops and households.',
    original_language: 'en',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    constituency: 'Coimbatore North',
    locality: 'Cross Cut Road, Gandhipuram',
    latitude: 11.0183,
    longitude: 76.9644,
    severity: 'HIGH',
    status: 'RESOLVED',
    assigned_representative_id: 'rep-ccmc-01',
    is_anonymous: false,
    submitter_name: 'Soundararajan V',
    submitter_email: 'soundar.cbe@example.com',
    submitter_phone: '9789012345',
    submitter_language: 'en',
    created_at: '2026-08-14T08:00:00Z',
    updated_at: '2026-08-15T16:00:00Z',
    updates: [
      {
        id: 'upd-201',
        complaint_id: 'complaint-sample-02',
        status: 'EMAIL_SENT',
        message: 'Dispatched to Coimbatore City Municipal Corporation water works division.',
        is_public: true,
        created_at: '2026-08-14T08:02:00Z',
      },
      {
        id: 'upd-202',
        complaint_id: 'complaint-sample-02',
        status: 'RESOLVED',
        message: 'Municipal engineering team replaced faulty pipe valve section. Water supply fully restored.',
        is_public: true,
        created_at: '2026-08-15T16:00:00Z',
      }
    ],
  },
  {
    id: 'complaint-sample-03',
    reference_number: 'MK-2026-319082',
    category: 'electricity',
    subcategory: 'Dangerous Hanging Cables',
    title: 'Low hanging high-tension electric wire near Government High School',
    description: 'Due to recent wind and heavy rains, the overhead wire has loosened and is hanging dangerously low (around 7 feet above road level) right in front of the school gate.',
    original_language: 'en',
    state: 'Tamil Nadu',
    district: 'Madurai',
    city: 'Madurai',
    constituency: 'Madurai Central',
    locality: 'Simmakkal North Street',
    latitude: 9.9272,
    longitude: 78.1215,
    severity: 'URGENT',
    status: 'IN_PROGRESS',
    assigned_representative_id: 'rep-madurai-01',
    is_anonymous: false,
    submitter_name: 'Meenakshi Sundaram',
    submitter_email: 'meenakshi.mdu@example.com',
    submitter_phone: '9443012345',
    submitter_language: 'en',
    created_at: '2026-08-17T11:00:00Z',
    updated_at: '2026-08-17T13:45:00Z',
    updates: [
      {
        id: 'upd-301',
        complaint_id: 'complaint-sample-03',
        status: 'EMAIL_SENT',
        message: 'Priority urgent alert dispatched to TANGEDCO Madurai Central Division.',
        is_public: true,
        created_at: '2026-08-17T11:02:00Z',
      },
      {
        id: 'upd-302',
        complaint_id: 'complaint-sample-03',
        status: 'IN_PROGRESS',
        message: 'TANGEDCO line crew on site to tension and secure overhead cables.',
        is_public: true,
        created_at: '2026-08-17T13:45:00Z',
      }
    ],
  }
];

// In-Memory & Local Storage Store Singleton for SSR/CSR
class MockDataStore {
  private complaints: Complaint[] = [...INITIAL_COMPLAINTS];
  private representatives: Representative[] = [...INITIAL_REPRESENTATIVES];

  constructor() {
    this.reloadFromStorage();
  }

  public reloadFromStorage() {
    if (typeof window !== 'undefined') {
      const storedComplaints = localStorage.getItem('mk_complaints');
      if (storedComplaints) {
        try {
          const parsed = JSON.parse(storedComplaints);
          if (Array.isArray(parsed)) {
            const existingIds = new Set(parsed.map((c: any) => c.reference_number?.toUpperCase() || c.id));
            const missingDefaults = INITIAL_COMPLAINTS.filter(
              c => !existingIds.has(c.reference_number?.toUpperCase()) && !existingIds.has(c.id)
            );
            this.complaints = [...parsed, ...missingDefaults];
          }
        } catch {
          this.complaints = [...INITIAL_COMPLAINTS];
        }
      }
      const storedReps = localStorage.getItem('mk_representatives');
      if (storedReps) {
        try {
          const parsed = JSON.parse(storedReps);
          if (Array.isArray(parsed)) {
            const existingIds = new Set(parsed.map((r: any) => r.id));
            const missingDefaults = INITIAL_REPRESENTATIVES.filter(r => !existingIds.has(r.id));
            this.representatives = [...parsed, ...missingDefaults];
          }
        } catch {
          this.representatives = [...INITIAL_REPRESENTATIVES];
        }
      }
    }
  }

  private persist() {
    if (typeof window !== 'undefined') {
      localStorage.setItem('mk_complaints', JSON.stringify(this.complaints));
      localStorage.setItem('mk_representatives', JSON.stringify(this.representatives));
    }
  }

  public getComplaints(): Complaint[] {
    return this.complaints;
  }

  public getComplaintByReference(ref: string): Complaint | undefined {
    return this.complaints.find(c => c.reference_number.toUpperCase() === ref.trim().toUpperCase());
  }

  public getComplaintById(id: string): Complaint | undefined {
    return this.complaints.find(c => c.id === id);
  }

  public addComplaint(complaint: Complaint): Complaint {
    this.complaints.unshift(complaint);
    this.persist();
    return complaint;
  }

  public updateComplaintStatus(
    id: string, 
    status: any, 
    publicMessage?: string, 
    assignedRepId?: string
  ): Complaint | null {
    const complaint = this.complaints.find(c => c.id === id);
    if (!complaint) return null;

    complaint.status = status;
    complaint.updated_at = new Date().toISOString();
    if (assignedRepId) {
      complaint.assigned_representative_id = assignedRepId;
    }

    if (publicMessage) {
      if (!complaint.updates) complaint.updates = [];
      complaint.updates.unshift({
        id: 'upd-' + Date.now(),
        complaint_id: id,
        status,
        message: publicMessage,
        is_public: true,
        created_at: new Date().toISOString(),
      });
    }

    this.persist();
    return complaint;
  }

  public getRepresentatives(): Representative[] {
    return this.representatives;
  }

  public getRepresentativeById(id: string): Representative | undefined {
    return this.representatives.find(r => r.id === id);
  }

  public addRepresentative(rep: Representative): Representative {
    this.representatives.unshift(rep);
    this.persist();
    return rep;
  }

  public updateRepresentative(id: string, updates: Partial<Representative>): Representative | null {
    const rep = this.representatives.find(r => r.id === id);
    if (!rep) return null;
    Object.assign(rep, updates, { updated_at: new Date().toISOString() });
    this.persist();
    return rep;
  }
}

export const mockStore = new MockDataStore();
