export interface CivicCategory {
  id: string;
  nameEn: string;
  nameTa: string;
  icon: string;
  descriptionEn: string;
  descriptionTa: string;
  subcategoriesEn: string[];
  subcategoriesTa: string[];
}

export const CIVIC_CATEGORIES: CivicCategory[] = [
  {
    id: 'roads',
    nameEn: 'Roads & Footpaths',
    nameTa: 'சாலைகள் & நடைபாதைகள்',
    icon: 'Road',
    descriptionEn: 'Potholes, damaged tarmac, broken sidewalks, missing speed breakers',
    descriptionTa: 'குழிகள், சேதமடைந்த தார்ச்சாலை, உடைந்த நடைபாதை, வேகத்தடைகள்',
    subcategoriesEn: ['Potholes', 'Damaged Tarmac', 'Broken Footpath / Paver Blocks', 'Speed Breaker Issue', 'Encroachment on Road'],
    subcategoriesTa: ['சாலை குழிகள்', 'சேதமடைந்த சாலை', 'உடைந்த நடைபாதை', 'வேகத்தடை பிரச்சனை', 'சாலை ஆக்கிரமிப்பு'],
  },
  {
    id: 'water',
    nameEn: 'Water Supply',
    nameTa: 'குடிநீர் விநியோகம்',
    icon: 'Droplets',
    descriptionEn: 'No water supply, contaminated water, pipeline leakages, low pressure',
    descriptionTa: 'குடிநீர் தட்டுப்பாடு, அசுத்தமான குடிநீர், குழாய் கசிவு, குறைந்த அழுத்தம்',
    subcategoriesEn: ['No Drinking Water Supply', 'Contaminated / Muddy Water', 'Pipeline Burst / Leakage', 'Low Water Pressure', 'Irregular Supply Timings'],
    subcategoriesTa: ['குடிநீர் விநியோகம் இல்லை', 'அசுத்தமான குடிநீர்', 'குழாய் உடைப்பு / கசிவு', 'குறைந்த நீர் அழுத்தம்', 'ஒழுங்கற்ற விநியோக நேரம்'],
  },
  {
    id: 'electricity',
    nameEn: 'Electricity & Power',
    nameTa: 'மின்சாரம் & மின்வாரியம்',
    icon: 'Zap',
    descriptionEn: 'Power cuts, transformer sparks, low voltage, hanging electrical cables',
    descriptionTa: 'மின்தடை, டிரான்ஸ்பார்மர் தீப்பொறி, குறைந்த மின்னழுத்தம், தொங்கும் மின் கம்பிகள்',
    subcategoriesEn: ['Unannounced Power Outage', 'Low / Fluctuating Voltage', 'Dangerous Hanging Cables', 'Transformer Issue / Sparking', 'Billing & Meter Defect'],
    subcategoriesTa: ['அறிவிக்கப்படாத மின்தடை', 'குறைந்த மின்னழுத்தம்', 'தொங்கும் ஆபத்தான மின்கம்பிகள்', 'டிரான்ஸ்பார்மர் கோளாறு', 'மின் அளவி கோளாறு'],
  },
  {
    id: 'drainage',
    nameEn: 'Drainage & Sewage',
    nameTa: 'கழிவுநீர் & வடிகால்',
    icon: 'Waves',
    descriptionEn: 'Overflowing sewage, blocked stormwater drains, open manholes',
    descriptionTa: 'கழிவுநீர் வழிதல், அடைபட்ட மழைநீர் வடிகால், திறந்திருக்கும் பாதாள சாக்கடை',
    subcategoriesEn: ['Sewage Overflow on Street', 'Blocked Stormwater Drain', 'Missing / Broken Manhole Lid', 'Foul Smell & Backflow', 'Waterlogging During Rains'],
    subcategoriesTa: ['தெருவில் கழிவுநீர் வழிதல்', 'மழைநீர் வடிகால் அடைப்பு', 'சாக்கடை மூடி உடைப்பு', 'துர்நாற்றம் & கழிவுநீர் தேக்கம்', 'மழைக்கால நீர் தேக்கம்'],
  },
  {
    id: 'garbage',
    nameEn: 'Garbage & Sanitation',
    nameTa: 'குப்பை மேலாண்மை & தூய்மை',
    icon: 'Trash2',
    descriptionEn: 'Uncollected trash, illegal dumping, missing dustbins, overflowing bins',
    descriptionTa: 'அகற்றப்படாத குப்பைகள், திறந்தவெளி குப்பை கொட்டுதல், நிரம்பிய தொட்டிகள்',
    subcategoriesEn: ['Garbage Not Collected', 'Overflowing Public Dustbin', 'Illegal Open Waste Dumping', 'Dead Animal Removal', 'Debris & Construction Waste'],
    subcategoriesTa: ['குப்பை அள்ளப்படாமை', 'நிரம்பி வழியும் குப்பை தொட்டி', 'திறந்தவெளி குப்பை கொட்டுதல்', 'இறந்த விலங்குகள் அகற்றுதல்', 'கட்டுமான கழிவுகள்'],
  },
  {
    id: 'street-lights',
    nameEn: 'Street Lights',
    nameTa: 'தெருவிளக்குகள்',
    icon: 'Lightbulb',
    descriptionEn: 'Non-functional lights, flickering bulbs, dark stretches, damaged poles',
    descriptionTa: 'எரியாத தெருவிளக்குகள், மின்கம்ப சேதம், ஒளிராத இருண்ட பகுதிகள்',
    subcategoriesEn: ['Street Light Not Working', 'Continuous Day-time Burning', 'Damaged / Tilted Electric Pole', 'Entire Street in Darkness', 'High-Mast Tower Failure'],
    subcategoriesTa: ['தெருவிளக்கு எரியவில்லை', 'பகலிலும் விளக்கு எரிதல்', 'சேதமடைந்த மின்கம்பம்', 'முழு தெருவும் இருட்டில் உள்ளது', 'உயர் மின் கோபுர விளக்கு கோளாறு'],
  },
  {
    id: 'transport',
    nameEn: 'Public Transport',
    nameTa: 'பொதுப்போக்குவரத்து',
    icon: 'Bus',
    descriptionEn: 'Irregular bus service, damaged bus stops, rash driving, route cuts',
    descriptionTa: 'ஒழுங்கற்ற பேருந்து சேவை, சேதமடைந்த பேருந்து நிறுத்தம், வேகமான ஓட்டுதல்',
    subcategoriesEn: ['Irregular Bus Timings', 'Missing / Damaged Bus Shelter', 'Driver Rash Driving / Skipping Stop', 'Overcrowding & Lack of Buses', 'Auto/Taxi Fare Overcharging'],
    subcategoriesTa: ['ஒழுங்கற்ற பேருந்து நேரம்', 'சேதமடைந்த பேருந்து நிழற்குடை', 'பேருந்து நிற்காமல் செல்லுதல்', 'கூடுதல் பேருந்துகள் தேவை', 'அதிக ஆட்டோ கட்டணம்'],
  },
  {
    id: 'healthcare',
    nameEn: 'Public Healthcare',
    nameTa: 'பொது சுகாதாரம் & மருத்துவமனைகள்',
    icon: 'HeartPulse',
    descriptionEn: 'PHC facilities, mosquito breeding, doctor absence, medicine shortages',
    descriptionTa: 'ஆரம்ப சுகாதார நிலையம், கொசு மருந்து தெளிப்பு, மருத்துவர் வருகை, மருந்து பற்றாக்குறை',
    subcategoriesEn: ['Mosquito Fogging Required', 'Primary Health Centre (PHC) Service', 'Lack of Essential Medicines', 'Hygiene in Public Hospital', 'Vaccination Facility'],
    subcategoriesTa: ['கொசு மருந்து அடிக்க வேண்டும்', 'ஆரம்ப சுகாதார நிலைய சேவை', 'மருந்து பற்றாக்குறை', 'மருத்துவமனை தூய்மை இன்மை', 'தடுப்பூசி சேவை'],
  },
  {
    id: 'education',
    nameEn: 'Government Schools & Anganwadis',
    nameTa: 'அரசு பள்ளிகள் & அங்கன்வாடிகள்',
    icon: 'GraduationCap',
    descriptionEn: 'School infrastructure, missing restrooms, drinking water, noon meal quality',
    descriptionTa: 'பள்ளி உள்கட்டமைப்பு, கழிப்பறை வசதி, குடிநீர் வசதி, மதிய உணவு தரம்',
    subcategoriesEn: ['Damaged Classrooms / Building', 'Lack of Clean Restrooms', 'Noon Meal Quality Issue', 'Lack of Drinking Water', 'Safety Around School Zone'],
    subcategoriesTa: ['சேதமடைந்த வகுப்பறைகள்', 'சுத்தமான கழிப்பறை இன்மை', 'மதிய உணவு தரம்', 'குடிநீர் வசதி இன்மை', 'பள்ளி பாதுகாப்பு'],
  },
  {
    id: 'traffic',
    nameEn: 'Traffic & Road Safety',
    nameTa: 'போக்குவரத்து & பாதுகாப்பு',
    icon: 'ShieldAlert',
    descriptionEn: 'Malfunctioning traffic signals, illegal parking, zebra crossing missing',
    descriptionTa: 'செயலிழந்த போக்குவரத்து சிக்னல்கள், முறையற்ற பார்க்கிங், எச்சரிக்கை பலகைகள்',
    subcategoriesEn: ['Traffic Signal Not Working', 'Illegal Parking Blocking Road', 'Missing Signboards & Markings', 'Dangerous U-turn Spot', 'Lack of Traffic Police at Peak Hours'],
    subcategoriesTa: ['சிக்னல் வேலை செய்யவில்லை', 'முறையற்ற பார்க்கிங்', 'எச்சரிக்கை பலகை இன்மை', 'ஆபத்தான திருப்பம்', 'போக்குவரத்து நெரிசல்'],
  },
  {
    id: 'gov-services',
    nameEn: 'Government Services & E-Sevai',
    nameTa: 'அரசு சேவைகள் & இ-சேவை',
    icon: 'FileText',
    descriptionEn: 'Ration card delays, patta transfer issues, certificate delays, bribery/touts',
    descriptionTa: 'ரேஷன் அட்டை தாமதம், பட்டா மாறுதல், சான்றிதழ் தாமதம், இ-சேவை மைய சேவை',
    subcategoriesEn: ['Ration Card / PDS Issue', 'Patta / Chitta Land Records', 'Birth / Death / Community Certificate', 'Pension & Welfare Scheme', 'E-Sevai Centre Grievance'],
    subcategoriesTa: ['ரேஷன் கடை / அட்டை பிரச்சனை', 'பட்டா / சிட்டா மாறுதல்', 'சான்றிதழ் பெறுவதில் தாமதம்', 'முதியோர் ஓய்வூதியம்', 'இ-சேவை மையம் புகார்'],
  },
  {
    id: 'public-safety',
    nameEn: 'Public Safety & Law',
    nameTa: 'பொது பாதுகாப்பு & சட்டம் ஒழுங்கு',
    icon: 'Shield',
    descriptionEn: 'Dark alleys, anti-social gatherings, unauthorized alcohol sales, noise pollution',
    descriptionTa: 'இருண்ட பாதைகள், சமூக விரோத செயல்கள், ஒலி மாசு, பாதுகாப்பின்மை',
    subcategoriesEn: ['Anti-social Elements Gathering', 'Loudspeaker / Noise Pollution', 'Unauthorized Liquor / Substance Sales', 'Street Harassment Concerns', 'CCTV Camera Requirement'],
    subcategoriesTa: ['சமூக விரோதிகள் நடமாட்டம்', 'அதிக ஒலிபெருக்கி சத்தம்', 'சட்டவிரோத மது விற்பனை', 'பெண்கள் பாதுகாப்பு', 'CCTV கேமரா தேவை'],
  },
  {
    id: 'environment',
    nameEn: 'Environment & Lakes',
    nameTa: 'சுற்றுச்சூழல் & ஏரிகள்',
    icon: 'TreePine',
    descriptionEn: 'Lake encroachment, sewage in water bodies, tree cutting, chemical fumes',
    descriptionTa: 'ஏரி ஆக்கிரமிப்பு, நீர்நிலைகளில் கழிவுநீர், மரம் வெட்டுதல், காற்று மாசு',
    subcategoriesEn: ['Lake / Waterbody Encroachment', 'Industrial Chemical Discharge', 'Illegal Tree Cutting', 'Air & Smoke Pollution', 'Plastic Ban Violation'],
    subcategoriesTa: ['ஏரி ஆக்கிரமிப்பு', 'தொழிற்சாலை கழிவு நீர்', 'மரம் வெட்டுதல்', 'காற்று மாசு', 'பிளாஸ்டிக் பயன்பாடு'],
  },
  {
    id: 'other',
    nameEn: 'Other Public Grievance',
    nameTa: 'பிற பொதுப் புகார்கள்',
    icon: 'HelpCircle',
    descriptionEn: 'Any other general public or civic infrastructure grievance',
    descriptionTa: 'மற்ற பிற பொது பிரச்சனைகள் மற்றும் அடிப்படை வசதி புகார்கள்',
    subcategoriesEn: ['Park / Playground Maintenance', 'Cemetery / Burial Ground Issue', 'Stray Cattle / Animals', 'General Civic Issue'],
    subcategoriesTa: ['பூங்கா / விளையாட்டு மைதானம்', 'சுடுகாடு / இடுகாடு பராமரிப்பு', 'தெரு மாடுகள் பிரச்சனை', 'பொதுவான குறைபாடு'],
  },
];
