export interface DistrictData {
  id: string;
  nameEn: string;
  nameTa: string;
  headquarters: string;
  constituenciesEn: string[];
  constituenciesTa: string[];
}

export const TAMIL_NADU_DISTRICTS: DistrictData[] = [
  {
    id: 'chennai',
    nameEn: 'Chennai',
    nameTa: 'சென்னை',
    headquarters: 'Chennai',
    constituenciesEn: ['Dr. Radhakrishnan Nagar', 'Perambur', 'Kolathur', 'Villivakkam', 'Thiru-Vi-Ka-Nagar', 'Egmore', 'Royapuram', 'Harbour', 'Chepauk-Thiruvallikeni', 'Thousand Lights', 'Anna Nagar', 'Virugampakkam', 'Saidapet', 'Thiyagarayanagar (T.Nagar)', 'Mylapore', 'Velachery', 'Sholinganallur', 'Alandur'],
    constituenciesTa: ['டாக்டர் ராதாகிருஷ்ணன் நகர்', 'பெரம்பூர்', 'கொளத்தூர்', 'வில்லிவாக்கம்', 'திரு.வி.க நகர்', 'எழும்பூர்', 'ராயபுரம்', 'துறைமுகம்', 'சேப்பாக்கம்-திருவல்லிக்கேணி', 'ஆயிரம் விளக்கு', 'அண்ணா நகர்', 'விருகம்பாக்கம்', 'சைதாப்பேட்டை', 'தியாகராய நகர்', 'மயிலாப்பூர்', 'வேளச்சேரி', 'சோழிங்கநல்லூர்', 'ஆலந்தூர்'],
  },
  {
    id: 'coimbatore',
    nameEn: 'Coimbatore',
    nameTa: 'கோயம்புத்தூர்',
    headquarters: 'Coimbatore',
    constituenciesEn: ['Coimbatore North', 'Coimbatore South', 'Kavundampalayam', 'Singanallur', 'Sulur', 'Thondamuthur', 'Kinathukadavu', 'Pollachi', 'Valparai', 'Mettupalayam'],
    constituenciesTa: ['கோயம்புத்தூர் வடக்கு', 'கோயம்புத்தூர் தெற்கு', 'கவுண்டம்பாளையம்', 'சிங்காநல்லூர்', 'சூலூர்', 'தொண்டாமுத்தூர்', 'கிணத்துக்கடவு', 'பொள்ளாச்சி', 'வால்பாறை', 'மேட்டுப்பாளையம்'],
  },
  {
    id: 'madurai',
    nameEn: 'Madurai',
    nameTa: 'மதுரை',
    headquarters: 'Madurai',
    constituenciesEn: ['Madurai North', 'Madurai South', 'Madurai Central', 'Madurai West', 'Madurai East', 'Thiruparankundram', 'Thirumangalam', 'Melur', 'Usilampatti', 'Sholavandan'],
    constituenciesTa: ['மதுரை வடக்கு', 'மதுரை தெற்கு', 'மதுரை மத்தி', 'மதுரை மேற்கு', 'மதுரை கிழக்கு', 'திருப்பரங்குன்றம்', 'திருமங்கலம்', 'மேலூர்', 'உசிலம்பட்டி', 'சோழவந்தான்'],
  },
  {
    id: 'tiruchirappalli',
    nameEn: 'Tiruchirappalli (Trichy)',
    nameTa: 'திருச்சிராப்பள்ளி',
    headquarters: 'Tiruchirappalli',
    constituenciesEn: ['Tiruchirappalli West', 'Tiruchirappalli East', 'Srirangam', 'Thiruverumbur', 'Manachanallur', 'Musiri', 'Thuraiyur', 'Lalgudi', 'Manapparai'],
    constituenciesTa: ['திருச்சிராப்பள்ளி மேற்கு', 'திருச்சிராப்பள்ளி கிழக்கு', 'ஸ்ரீரங்கம்', 'திருவெறும்பூர்', 'மண்ணச்சநல்லூர்', 'முசிறி', 'துறையூர்', 'லால்குடி', 'மணப்பாறை'],
  },
  {
    id: 'salem',
    nameEn: 'Salem',
    nameTa: 'சேலம்',
    headquarters: 'Salem',
    constituenciesEn: ['Salem North', 'Salem South', 'Salem West', 'Veerapandi', 'Yercaud', 'Omalur', 'Mettur', 'Edappadi', 'Sankari', 'Attur', 'Gangavalli'],
    constituenciesTa: ['சேலம் வடக்கு', 'சேலம் தெற்கு', 'சேலம் மேற்கு', 'வீரபாண்டி', 'ஏற்காடு', 'ஓமலூர்', 'மேட்டூர்', 'எடப்பாடி', 'சங்ககிரி', 'ஆத்தூர்', 'கெங்கவல்லி'],
  },
  {
    id: 'tirunelveli',
    nameEn: 'Tirunelveli',
    nameTa: 'திருநெல்வேலி',
    headquarters: 'Tirunelveli',
    constituenciesEn: ['Tirunelveli', 'Palayamkottai', 'Ambasamudram', 'Nanguneri', 'Radhapuram'],
    constituenciesTa: ['திருநெல்வேலி', 'பாளையங்கோட்டை', 'அம்பாசமுத்திரம்', 'நாங்குநேரி', 'ராதாபுரம்'],
  },
  {
    id: 'kanchipuram',
    nameEn: 'Kanchipuram',
    nameTa: 'காஞ்சிபுரம்',
    headquarters: 'Kanchipuram',
    constituenciesEn: ['Kanchipuram', 'Sriperumbudur', 'Uthiramerur'],
    constituenciesTa: ['காஞ்சிபுரம்', 'ஸ்ரீபெரும்புதூர்', 'உத்திரமேரூர்'],
  },
  {
    id: 'chengalpattu',
    nameEn: 'Chengalpattu',
    nameTa: 'செங்கல்பட்டு',
    headquarters: 'Chengalpattu',
    constituenciesEn: ['Chengalpattu', 'Tambaram', 'Pallavaram', 'Madurantakam', 'Cheyyur', 'Thiruporur'],
    constituenciesTa: ['செங்கல்பட்டு', 'தாம்பரம்', 'பல்லாவரம்', 'மதுராந்தகம்', 'செய்யூர்', 'திருப்போரூர்'],
  },
  {
    id: 'thiruvallur',
    nameEn: 'Thiruvallur',
    nameTa: 'திருவள்ளூர்',
    headquarters: 'Thiruvallur',
    constituenciesEn: ['Thiruvallur', 'Avadi', 'Poonamallee', 'Ambattur', 'Madavaram', 'Gummidipoondi', 'Ponneri', 'Tiruttani'],
    constituenciesTa: ['திருவள்ளூர்', 'ஆவடி', 'பூந்தமல்லி', 'அம்பத்தூர்', 'மாதவரம்', 'கும்மிடிப்பூண்டி', 'பொன்னேரி', 'திருத்தணி'],
  },
  {
    id: 'thanjavur',
    nameEn: 'Thanjavur',
    nameTa: 'தஞ்சாவூர்',
    headquarters: 'Thanjavur',
    constituenciesEn: ['Thanjavur', 'Kumbakonam', 'Papanasam', 'Thiruvaiyaru', 'Orathanadu', 'Pattukkottai', 'Peravurani', 'Thiruvidaimarudur'],
    constituenciesTa: ['தஞ்சாவூர்', 'கும்பகோணம்', 'பாபநாசம்', 'திருவையாறு', 'ஒரத்தநாடு', 'பட்டுக்கோட்டை', 'பேராவூரணி', 'திருவிடைமருதூர்'],
  },
  {
    id: 'erode',
    nameEn: 'Erode',
    nameTa: 'ஈரோடு',
    headquarters: 'Erode',
    constituenciesEn: ['Erode East', 'Erode West', 'Modakkurichi', 'Perundurai', 'Bhavani', 'Anthiyur', 'Gobichettipalayam', 'Bhavanisagar'],
    constituenciesTa: ['ஈரோடு கிழக்கு', 'ஈரோடு மேற்கு', 'மொடக்குறிச்சி', 'பெருந்துறை', 'பவானி', 'அந்தியூர்', 'கோபிசெட்டிபாளையம்', 'பவானிசாகர்'],
  },
  {
    id: 'tiruppur',
    nameEn: 'Tiruppur',
    nameTa: 'திருப்பூர்',
    headquarters: 'Tiruppur',
    constituenciesEn: ['Tiruppur North', 'Tiruppur South', 'Palladam', 'Udumalaipettai', 'Madathukulam', 'Dharapuram', 'Kangayam', 'Avanashi'],
    constituenciesTa: ['திருப்பூர் வடக்கு', 'திருப்பூர் தெற்கு', 'பல்லடம்', 'உடுமலைப்பேட்டை', 'மடத்துக்குளம்', 'தாராபுரம்', 'காங்கேயம்', 'அவினாசி'],
  },
  {
    id: 'vellore',
    nameEn: 'Vellore',
    nameTa: 'வேலூர்',
    headquarters: 'Vellore',
    constituenciesEn: ['Vellore', 'Anaikattu', 'Kilvaithinankuppam', 'Gudiyattam'],
    constituenciesTa: ['வேலூர்', 'அணைக்கட்டு', 'கே.வி.குப்பம்', 'குடியாத்தம்'],
  },
  {
    id: 'dindigul',
    nameEn: 'Dindigul',
    nameTa: 'திண்டுக்கல்',
    headquarters: 'Dindigul',
    constituenciesEn: ['Dindigul', 'Palani', 'Oddanchatram', 'Athoor', 'Nilakkottai', 'Natham', 'Vedasandur'],
    constituenciesTa: ['திண்டுக்கல்', 'பழனி', 'ஒட்டன்சத்திரம்', 'ஆத்தூர்', 'நிலக்கோட்டை', 'நத்தம்', 'வேடசந்தூர்'],
  },
  {
    id: 'cuddalore',
    nameEn: 'Cuddalore',
    nameTa: 'கடலூர்',
    headquarters: 'Cuddalore',
    constituenciesEn: ['Cuddalore', 'Panruti', 'Chidambaram', 'Kattumannarkoil', 'Kurinjipadi', 'Bhuvanagiri', 'Vridhachalam', 'Tittakudi', 'Neyveli'],
    constituenciesTa: ['கடலூர்', 'பண்ருட்டி', 'சிதம்பரம்', 'காட்டுமன்னார்கோவில்', 'குறிஞ்சிப்பாடி', 'புவனகிரி', 'விருத்தாசலம்', 'திட்டக்குடி', 'நெய்வேலி'],
  },
  {
    id: 'thoothukudi',
    nameEn: 'Thoothukudi (Tuticorin)',
    nameTa: 'தூத்துக்குடி',
    headquarters: 'Thoothukudi',
    constituenciesEn: ['Thoothukudi', 'Tiruchendur', 'Srivaikuntam', 'Ottapidaram', 'Kovilpatti', 'Vilathikulam'],
    constituenciesTa: ['தூத்துக்குடி', 'திருச்செந்தூர்', 'ஸ்ரீவைகுண்டம்', 'ஒட்டப்பிடாரம்', 'கோவில்பட்டி', 'விளாத்திகுளம்'],
  },
  {
    id: 'kanyakumari',
    nameEn: 'Kanyakumari',
    nameTa: 'கன்னியாகுமரி',
    headquarters: 'Nagercoil',
    constituenciesEn: ['Kanyakumari', 'Nagercoil', 'Colachel', 'Padmanabhapuram', 'Vilavancode', 'Killiyoor'],
    constituenciesTa: ['கன்னியாகுமரி', 'நாகர்கோவில்', 'குளச்சல்', 'பத்மநாபபுரம்', 'விளவங்கோடு', 'கிள்ளியூர்'],
  },
  {
    id: 'dharmapuri',
    nameEn: 'Dharmapuri',
    nameTa: 'தருமபுரி',
    headquarters: 'Dharmapuri',
    constituenciesEn: ['Dharmapuri', 'Palacodu', 'Pennagaram', 'Harur', 'Pappireddippatti'],
    constituenciesTa: ['தருமபுரி', 'பாலக்கோடு', 'பென்னாகரம்', 'அரூர்', 'பாப்பிரெட்டிப்பட்டி'],
  },
  {
    id: 'krishnagiri',
    nameEn: 'Krishnagiri',
    nameTa: 'கிருஷ்ணகிரி',
    headquarters: 'Krishnagiri',
    constituenciesEn: ['Krishnagiri', 'Hosur', 'Uthangarai', 'Bargur', 'Singarapettai', 'Thalli'],
    constituenciesTa: ['கிருஷ்ணகிரி', 'ஓசூர்', 'உத்தங்கரை', 'பர்கூர்', 'சிங்காரப்பேட்டை', 'தளி'],
  },
  {
    id: 'namakkal',
    nameEn: 'Namakkal',
    nameTa: 'நாமக்கல்',
    headquarters: 'Namakkal',
    constituenciesEn: ['Namakkal', 'Rasipuram', 'Senthamangalam', 'Paramathi-Velur', 'Tiruchengodu', 'Kumarapalayam'],
    constituenciesTa: ['நாமக்கல்', 'ராசிபுரம்', 'சேந்தமங்கலம்', 'பரமத்தி-வேலூர்', 'திருச்செங்கோடு', 'குமாரபாளையம்'],
  },
  {
    id: 'villupuram',
    nameEn: 'Villupuram',
    nameTa: 'விழுப்புரம்',
    headquarters: 'Villupuram',
    constituenciesEn: ['Villupuram', 'Vikravandi', 'Tindivanam', 'Vanur', 'Mailam', 'Gingee'],
    constituenciesTa: ['விழுப்புரம்', 'விக்ரவாண்டி', 'திண்டிவனம்', 'வானூர்', 'மயிலம்', 'செஞ்சி'],
  },
  {
    id: 'nagapattinam',
    nameEn: 'Nagapattinam',
    nameTa: 'நாகப்பட்டினம்',
    headquarters: 'Nagapattinam',
    constituenciesEn: ['Nagapattinam', 'Kilvelur', 'Vedaranyam'],
    constituenciesTa: ['நாகப்பட்டினம்', 'கீழ்வேளூர்', 'வேதாரண்யம்'],
  },
  {
    id: 'pudukkottai',
    nameEn: 'Pudukkottai',
    nameTa: 'புதுக்கோட்டை',
    headquarters: 'Pudukkottai',
    constituenciesEn: ['Pudukkottai', 'Gandarvakottai', 'Viralimalai', 'Thirumayam', 'Alangudi', 'Aranthangi'],
    constituenciesTa: ['புதுக்கோட்டை', 'கந்தர்வக்கோட்டை', 'விராலிமலை', 'திருமயம்', 'ஆலங்குடி', 'அறந்தாங்கி'],
  },
  {
    id: 'ramanathapuram',
    nameEn: 'Ramanathapuram',
    nameTa: 'ராமநாதபுரம்',
    headquarters: 'Ramanathapuram',
    constituenciesEn: ['Ramanathapuram', 'Paramakudi', 'Tiruvadanai', 'Mudukulathur'],
    constituenciesTa: ['ராமநாதபுரம்', 'பரமக்குடி', 'திருவாடானை', 'முதுகுளத்தூர்'],
  },
  {
    id: 'virudhunagar',
    nameEn: 'Virudhunagar',
    nameTa: 'விருதுநகர்',
    headquarters: 'Virudhunagar',
    constituenciesEn: ['Virudhunagar', 'Sivakasi', 'Sattur', 'Aruppukkottai', 'Tiruchuli', 'Rajapalayam', 'Srivilliputhur'],
    constituenciesTa: ['விருதுநகர்', 'சிவகாசி', 'சாத்தூர்', 'அருப்புக்கோட்டை', 'திருச்சுழி', 'ராஜபாளையம்', 'ஸ்ரீவில்லிபுத்தூர்'],
  },
  {
    id: 'sivaganga',
    nameEn: 'Sivaganga',
    nameTa: 'சிவகங்கை',
    headquarters: 'Sivaganga',
    constituenciesEn: ['Sivaganga', 'Karaikudi', 'Tiruppattur', 'Manamadurai'],
    constituenciesTa: ['சிவகங்கை', 'காரைக்குடி', 'திருப்பத்தூர்', 'மானாமதுரை'],
  },
  {
    id: 'nilgiris',
    nameEn: 'The Nilgiris',
    nameTa: 'நீலகிரி',
    headquarters: 'Udhagamandalam (Ooty)',
    constituenciesEn: ['Udhagamandalam', 'Coonoor', 'Gudalur'],
    constituenciesTa: ['உதகமண்டலம்', 'குன்னூர்', 'கூடலூர்'],
  },
  {
    id: 'theeni',
    nameEn: 'Theni',
    nameTa: 'தேனி',
    headquarters: 'Theni',
    constituenciesEn: ['Bodinayakanur', 'Periyakulam', 'Cumbum', 'Andipatti'],
    constituenciesTa: ['போடிநாயக்கனூர்', 'பெரியகுளம்', 'கம்பம்', 'ஆண்டிபட்டி'],
  },
  {
    id: 'karur',
    nameEn: 'Karur',
    nameTa: 'கரூர்',
    headquarters: 'Karur',
    constituenciesEn: ['Karur', 'Aravakurichi', 'Krishnarayapuram', 'Kulithalai'],
    constituenciesTa: ['கரூர்', 'அரவக்குறிச்சி', 'கிருஷ்ணராயபுரம்', 'குளித்தலை'],
  },
  {
    id: 'perambalur',
    nameEn: 'Perambalur',
    nameTa: 'பெரம்பலூர்',
    headquarters: 'Perambalur',
    constituenciesEn: ['Perambalur', 'Kunnam'],
    constituenciesTa: ['பெரம்பலூர்', 'குன்னம்'],
  },
  {
    id: 'ariyalur',
    nameEn: 'Ariyalur',
    nameTa: 'அரியலூர்',
    headquarters: 'Ariyalur',
    constituenciesEn: ['Ariyalur', 'Jayankondam'],
    constituenciesTa: ['அரியலூர்', 'ஜெயங்கொண்டம்'],
  },
  {
    id: 'thiruvarur',
    nameEn: 'Thiruvarur',
    nameTa: 'திருவாரூர்',
    headquarters: 'Thiruvarur',
    constituenciesEn: ['Thiruvarur', 'Mannargudi', 'Thiruthuraipoondi', 'Nannilam'],
    constituenciesTa: ['திருவாரூர்', 'மன்னார்குடி', 'திருத்துறைப்பூண்டி', 'நன்னிலம்'],
  },
  {
    id: 'tiruvannamalai',
    nameEn: 'Tiruvannamalai',
    nameTa: 'திருவண்ணாமலை',
    headquarters: 'Tiruvannamalai',
    constituenciesEn: ['Tiruvannamalai', 'Chengam', 'Polur', 'Arani', 'Cheyyar', 'Vandavasi', 'Kalasapakkam', 'Kilpennathur'],
    constituenciesTa: ['திருவண்ணாமலை', 'செங்கம்', 'போளூர்', 'ஆரணி', 'செய்யாறு', 'வந்தவாசி', 'கலசப்பாக்கம்', 'கீழ்பென்னாத்தூர்'],
  },
  {
    id: 'ranipet',
    nameEn: 'Ranipet',
    nameTa: 'ராணிப்பேட்டை',
    headquarters: 'Ranipet',
    constituenciesEn: ['Ranipet', 'Arcot', 'Sholinghur', 'Arakkonam'],
    constituenciesTa: ['ராணிப்பேட்டை', 'ஆற்காடு', 'சோளிங்கர்', 'அரக்கோணம்'],
  },
  {
    id: 'tirupathur',
    nameEn: 'Tirupathur',
    nameTa: 'திருப்பத்தூர்',
    headquarters: 'Tirupathur',
    constituenciesEn: ['Tirupathur', 'Vaniyambadi', 'Ambur', 'Jolarpet'],
    constituenciesTa: ['திருப்பத்தூர்', 'வாணியம்பாடி', 'ஆம்பூர்', 'ஜோலார்பேட்டை'],
  },
  {
    id: 'kallakurichi',
    nameEn: 'Kallakurichi',
    nameTa: 'கள்ளக்குறிச்சி',
    headquarters: 'Kallakurichi',
    constituenciesEn: ['Kallakurichi', 'Rishivandiyam', 'Sankarapuram', 'Ulundurpet'],
    constituenciesTa: ['கள்ளக்குறிச்சி', 'ரிஷிவந்தியம்', 'சங்கராபுரம்', 'உளுந்தூர்பேட்டை'],
  },
  {
    id: 'tenkasi',
    nameEn: 'Tenkasi',
    nameTa: 'தென்காசி',
    headquarters: 'Tenkasi',
    constituenciesEn: ['Tenkasi', 'Kadayanallur', 'Vasudevanallur', 'Sankarankovil', 'Alangulam'],
    constituenciesTa: ['தென்காசி', 'கடையநல்லூர்', 'வாசுதேவநல்லூர்', 'சங்கரன்கோவில்', 'ஆலங்குளம்'],
  },
  {
    id: 'mayiladuthurai',
    nameEn: 'Mayiladuthurai',
    nameTa: 'மயிலாடுதுறை',
    headquarters: 'Mayiladuthurai',
    constituenciesEn: ['Mayiladuthurai', 'Sirkazhi', 'Poompuhar'],
    constituenciesTa: ['மயிலாடுதுறை', 'சீர்காழி', 'பூம்புகார்'],
  },
];

export const TAMIL_NADU_DISTRICT_COORDINATES: Record<string, { lat: number; lng: number }> = {
  'chennai': { lat: 13.0827, lng: 80.2707 },
  'coimbatore': { lat: 11.0168, lng: 76.9558 },
  'madurai': { lat: 9.9252, lng: 78.1198 },
  'tiruchirappalli': { lat: 10.7905, lng: 78.7047 },
  'trichy': { lat: 10.7905, lng: 78.7047 },
  'salem': { lat: 11.6643, lng: 78.1460 },
  'tirunelveli': { lat: 8.7139, lng: 77.7567 },
  'tiruppur': { lat: 11.1085, lng: 77.3411 },
  'erode': { lat: 11.3410, lng: 77.7172 },
  'vellore': { lat: 12.9165, lng: 79.1325 },
  'thanjavur': { lat: 10.7870, lng: 79.1378 },
  'dindigul': { lat: 10.3673, lng: 77.9803 },
  'kanchipuram': { lat: 12.8342, lng: 79.7036 },
  'tiruvallur': { lat: 13.1432, lng: 79.9079 },
  'cuddalore': { lat: 11.7480, lng: 79.7714 },
  'nagapattinam': { lat: 10.7656, lng: 79.8424 },
  'thiruvarur': { lat: 10.7725, lng: 79.6365 },
  'mayiladuthurai': { lat: 11.1075, lng: 79.6524 },
  'pudukkottai': { lat: 10.3833, lng: 78.8001 },
  'sivaganga': { lat: 9.8433, lng: 78.4809 },
  'ramanathapuram': { lat: 9.3639, lng: 78.8395 },
  'virudhunagar': { lat: 9.5680, lng: 77.9624 },
  'theni': { lat: 10.0104, lng: 77.4768 },
  'tenkasi': { lat: 8.9594, lng: 77.3150 },
  'kanniyakumari': { lat: 8.0883, lng: 77.5385 },
  'thoothukudi': { lat: 8.7642, lng: 78.1348 },
  'tuticorin': { lat: 8.7642, lng: 78.1348 },
  'namakkal': { lat: 11.2189, lng: 78.1674 },
  'karur': { lat: 10.9601, lng: 78.0766 },
  'nilgiris': { lat: 11.4102, lng: 76.6950 },
  'ooty': { lat: 11.4102, lng: 76.6950 },
  'dharmapuri': { lat: 12.1211, lng: 78.1582 },
  'krishnagiri': { lat: 12.5186, lng: 78.2137 },
  'tirupathur': { lat: 12.4962, lng: 78.5663 },
  'ranipet': { lat: 12.9272, lng: 79.3330 },
  'tiruvannamalai': { lat: 12.2253, lng: 79.0747 },
  'villupuram': { lat: 11.9401, lng: 79.4861 },
  'kallakurichi': { lat: 11.7383, lng: 78.9639 },
  'perambalur': { lat: 11.2342, lng: 78.8820 },
  'ariyalur': { lat: 11.1401, lng: 79.0786 },
  'chengalpattu': { lat: 12.6841, lng: 79.9836 },
};

export function getDistrictCoordinates(districtName?: string): { lat: number; lng: number } {
  if (!districtName) return { lat: 13.0827, lng: 80.2707 }; // Default to Chennai, Tamil Nadu
  const key = districtName.toLowerCase().replace(/[^a-z]/g, '');
  for (const [dist, coords] of Object.entries(TAMIL_NADU_DISTRICT_COORDINATES)) {
    if (key.includes(dist) || dist.includes(key)) {
      return coords;
    }
  }
  return { lat: 13.0827, lng: 80.2707 };
}
